// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assets.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAssetObject = `-- name: CreateAssetObject :one
INSERT INTO objects(id,project_id,kind) VALUES($1,$2,'asset') RETURNING id, project_id, kind, schema_name, doc_kind, head_version_id, head_path, created_at, deleted_at
`

type CreateAssetObjectParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"projectId"`
}

func (q *Queries) CreateAssetObject(ctx context.Context, arg CreateAssetObjectParams) (Object, error) {
	row := q.db.QueryRow(ctx, createAssetObject, arg.ID, arg.ProjectID)
	var i Object
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.SchemaName,
		&i.DocKind,
		&i.HeadVersionID,
		&i.HeadPath,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const readyAssetFile = `-- name: ReadyAssetFile :one
SELECT project_id, sha256, storage_key, mime_type, size_bytes, width, height, duration_ms, blurhash, status, preview_key, created_at FROM asset_files WHERE project_id=$1 AND sha256=$2 AND status='ready'
`

type ReadyAssetFileParams struct {
	ProjectID uuid.UUID `json:"projectId"`
	Sha256    []byte    `json:"sha256"`
}

func (q *Queries) ReadyAssetFile(ctx context.Context, arg ReadyAssetFileParams) (AssetFile, error) {
	row := q.db.QueryRow(ctx, readyAssetFile, arg.ProjectID, arg.Sha256)
	var i AssetFile
	err := row.Scan(
		&i.ProjectID,
		&i.Sha256,
		&i.StorageKey,
		&i.MimeType,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.DurationMs,
		&i.Blurhash,
		&i.Status,
		&i.PreviewKey,
		&i.CreatedAt,
	)
	return i, err
}

const readyAssetUpload = `-- name: ReadyAssetUpload :one
SELECT u.id, f.project_id, f.sha256, f.storage_key, f.mime_type, f.size_bytes, f.width, f.height, f.duration_ms, f.blurhash, f.status, f.preview_key, f.created_at FROM asset_uploads u JOIN asset_files f ON f.project_id=u.project_id AND f.sha256=u.file_sha256
WHERE u.project_id=$1 AND u.id=$2 AND u.actor_id=$3 AND u.status='ready' AND f.status='ready'
`

type ReadyAssetUploadParams struct {
	ProjectID uuid.UUID `json:"projectId"`
	ID        uuid.UUID `json:"id"`
	ActorID   uuid.UUID `json:"actorId"`
}

type ReadyAssetUploadRow struct {
	ID         uuid.UUID `json:"id"`
	ProjectID  uuid.UUID `json:"projectId"`
	Sha256     []byte    `json:"sha256"`
	StorageKey string    `json:"storageKey"`
	MimeType   string    `json:"mimeType"`
	SizeBytes  int64     `json:"sizeBytes"`
	Width      *int32    `json:"width"`
	Height     *int32    `json:"height"`
	DurationMs *int32    `json:"durationMs"`
	Blurhash   *string   `json:"blurhash"`
	Status     string    `json:"status"`
	PreviewKey *string   `json:"previewKey"`
	CreatedAt  time.Time `json:"createdAt"`
}

func (q *Queries) ReadyAssetUpload(ctx context.Context, arg ReadyAssetUploadParams) (ReadyAssetUploadRow, error) {
	row := q.db.QueryRow(ctx, readyAssetUpload, arg.ProjectID, arg.ID, arg.ActorID)
	var i ReadyAssetUploadRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Sha256,
		&i.StorageKey,
		&i.MimeType,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.DurationMs,
		&i.Blurhash,
		&i.Status,
		&i.PreviewKey,
		&i.CreatedAt,
	)
	return i, err
}
