// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const actorCapabilities = `-- name: ActorCapabilities :many
SELECT DISTINCT unnest(r.capabilities)::text AS capability
FROM role_bindings b
JOIN roles r ON r.id = b.role_id
WHERE b.project_id = $1 AND b.actor_id = $2
ORDER BY 1
`

type ActorCapabilitiesParams struct {
	ProjectID uuid.UUID `json:"projectId"`
	ActorID   uuid.UUID `json:"actorId"`
}

func (q *Queries) ActorCapabilities(ctx context.Context, arg ActorCapabilitiesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, actorCapabilities, arg.ProjectID, arg.ActorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var capability string
		if err := rows.Scan(&capability); err != nil {
			return nil, err
		}
		items = append(items, capability)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const bindRole = `-- name: BindRole :exec
INSERT INTO role_bindings (project_id, actor_id, role_id) VALUES ($1, $2, $3)
`

type BindRoleParams struct {
	ProjectID uuid.UUID `json:"projectId"`
	ActorID   uuid.UUID `json:"actorId"`
	RoleID    uuid.UUID `json:"roleId"`
}

func (q *Queries) BindRole(ctx context.Context, arg BindRoleParams) error {
	_, err := q.db.Exec(ctx, bindRole, arg.ProjectID, arg.ActorID, arg.RoleID)
	return err
}

const createAPIToken = `-- name: CreateAPIToken :one
INSERT INTO api_tokens (id, project_id, actor_id, token_hash, scopes, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, actor_id, token_hash, scopes, environments, expires_at, last_used_at, revoked_at, created_at
`

type CreateAPITokenParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"projectId"`
	ActorID   uuid.UUID `json:"actorId"`
	TokenHash []byte    `json:"tokenHash"`
	Scopes    []string  `json:"scopes"`
	ExpiresAt time.Time `json:"expiresAt"`
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error) {
	row := q.db.QueryRow(ctx, createAPIToken,
		arg.ID,
		arg.ProjectID,
		arg.ActorID,
		arg.TokenHash,
		arg.Scopes,
		arg.ExpiresAt,
	)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ActorID,
		&i.TokenHash,
		&i.Scopes,
		&i.Environments,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createActor = `-- name: CreateActor :one
INSERT INTO actors (id, kind, project_id, display_name)
VALUES ($1, $2, $3, $4)
RETURNING id, kind, project_id, display_name, oidc_subject, email, disabled_at, created_at
`

type CreateActorParams struct {
	ID          uuid.UUID  `json:"id"`
	Kind        string     `json:"kind"`
	ProjectID   *uuid.UUID `json:"projectId"`
	DisplayName string     `json:"displayName"`
}

func (q *Queries) CreateActor(ctx context.Context, arg CreateActorParams) (Actor, error) {
	row := q.db.QueryRow(ctx, createActor,
		arg.ID,
		arg.Kind,
		arg.ProjectID,
		arg.DisplayName,
	)
	var i Actor
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ProjectID,
		&i.DisplayName,
		&i.OidcSubject,
		&i.Email,
		&i.DisabledAt,
		&i.CreatedAt,
	)
	return i, err
}

const createRole = `-- name: CreateRole :one
INSERT INTO roles (id, project_id, name, capabilities) VALUES ($1, $2, $3, $4)
RETURNING id, project_id, name, capabilities
`

type CreateRoleParams struct {
	ID           uuid.UUID `json:"id"`
	ProjectID    uuid.UUID `json:"projectId"`
	Name         string    `json:"name"`
	Capabilities []string  `json:"capabilities"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.Capabilities,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Capabilities,
	)
	return i, err
}

const getTokenPrincipal = `-- name: GetTokenPrincipal :one
SELECT t.id AS token_id, t.scopes, t.environments, t.expires_at,
       a.id AS actor_id, a.kind AS actor_kind, a.display_name,
       p.id AS project_id, p.slug AS project_slug
FROM api_tokens t
JOIN actors a ON a.id = t.actor_id
JOIN projects p ON p.id = t.project_id
WHERE t.token_hash = $1
  AND t.revoked_at IS NULL
  AND t.expires_at > now()
  AND a.disabled_at IS NULL
`

type GetTokenPrincipalRow struct {
	TokenID      uuid.UUID `json:"tokenId"`
	Scopes       []string  `json:"scopes"`
	Environments []string  `json:"environments"`
	ExpiresAt    time.Time `json:"expiresAt"`
	ActorID      uuid.UUID `json:"actorId"`
	ActorKind    string    `json:"actorKind"`
	DisplayName  string    `json:"displayName"`
	ProjectID    uuid.UUID `json:"projectId"`
	ProjectSlug  string    `json:"projectSlug"`
}

// Действующий токен вместе с его актором и проектом.
func (q *Queries) GetTokenPrincipal(ctx context.Context, tokenHash []byte) (GetTokenPrincipalRow, error) {
	row := q.db.QueryRow(ctx, getTokenPrincipal, tokenHash)
	var i GetTokenPrincipalRow
	err := row.Scan(
		&i.TokenID,
		&i.Scopes,
		&i.Environments,
		&i.ExpiresAt,
		&i.ActorID,
		&i.ActorKind,
		&i.DisplayName,
		&i.ProjectID,
		&i.ProjectSlug,
	)
	return i, err
}

const touchToken = `-- name: TouchToken :exec
UPDATE api_tokens SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchToken, id)
	return err
}
