// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: changesets.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const addChangesetObject = `-- name: AddChangesetObject :exec
INSERT INTO changeset_objects (changeset_id, object_id, base_version_id, working_version_id)
VALUES ($1, $2, $3, $4)
`

type AddChangesetObjectParams struct {
	ChangesetID      uuid.UUID  `json:"changesetId"`
	ObjectID         uuid.UUID  `json:"objectId"`
	BaseVersionID    *uuid.UUID `json:"baseVersionId"`
	WorkingVersionID uuid.UUID  `json:"workingVersionId"`
}

func (q *Queries) AddChangesetObject(ctx context.Context, arg AddChangesetObjectParams) error {
	_, err := q.db.Exec(ctx, addChangesetObject,
		arg.ChangesetID,
		arg.ObjectID,
		arg.BaseVersionID,
		arg.WorkingVersionID,
	)
	return err
}

const createChangeset = `-- name: CreateChangeset :one
INSERT INTO changesets (id, project_id, kind, title, description, owner_id, state)
VALUES ($1, $2, 'standard', $3, $4, $5, 'open')
RETURNING id, project_id, kind, title, description, owner_id, state, risk, targets, seq, content_hash, has_conflicts, created_at, updated_at, submitted_at, merged_at
`

type CreateChangesetParams struct {
	ID          uuid.UUID `json:"id"`
	ProjectID   uuid.UUID `json:"projectId"`
	Title       string    `json:"title"`
	Description *string   `json:"description"`
	OwnerID     uuid.UUID `json:"ownerId"`
}

func (q *Queries) CreateChangeset(ctx context.Context, arg CreateChangesetParams) (Changeset, error) {
	row := q.db.QueryRow(ctx, createChangeset,
		arg.ID,
		arg.ProjectID,
		arg.Title,
		arg.Description,
		arg.OwnerID,
	)
	var i Changeset
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Title,
		&i.Description,
		&i.OwnerID,
		&i.State,
		&i.Risk,
		&i.Targets,
		&i.Seq,
		&i.ContentHash,
		&i.HasConflicts,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubmittedAt,
		&i.MergedAt,
	)
	return i, err
}

const createObject = `-- name: CreateObject :one
INSERT INTO objects (id, project_id, kind, doc_kind) VALUES ($1, $2, 'document', $3)
RETURNING id, project_id, kind, schema_name, doc_kind, head_version_id, head_path, created_at, deleted_at
`

type CreateObjectParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"projectId"`
	DocKind   *string   `json:"docKind"`
}

func (q *Queries) CreateObject(ctx context.Context, arg CreateObjectParams) (Object, error) {
	row := q.db.QueryRow(ctx, createObject, arg.ID, arg.ProjectID, arg.DocKind)
	var i Object
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.SchemaName,
		&i.DocKind,
		&i.HeadVersionID,
		&i.HeadPath,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createWorkingVersion = `-- name: CreateWorkingVersion :one
INSERT INTO object_versions (id, project_id, object_id, state, changeset_id, parent_version_id, ir_version, path, body, body_hash, created_by)
VALUES ($1, $2, $3, 'working', $4, $5, $6, $7, $8, $9, $10)
RETURNING id, project_id, object_id, number, state, changeset_id, parent_version_id, schema_version, ir_version, path, body, body_hash, created_by, created_at, committed_at
`

type CreateWorkingVersionParams struct {
	ID              uuid.UUID  `json:"id"`
	ProjectID       uuid.UUID  `json:"projectId"`
	ObjectID        uuid.UUID  `json:"objectId"`
	ChangesetID     *uuid.UUID `json:"changesetId"`
	ParentVersionID *uuid.UUID `json:"parentVersionId"`
	IrVersion       *string    `json:"irVersion"`
	Path            *string    `json:"path"`
	Body            []byte     `json:"body"`
	BodyHash        []byte     `json:"bodyHash"`
	CreatedBy       uuid.UUID  `json:"createdBy"`
}

func (q *Queries) CreateWorkingVersion(ctx context.Context, arg CreateWorkingVersionParams) (ObjectVersion, error) {
	row := q.db.QueryRow(ctx, createWorkingVersion,
		arg.ID,
		arg.ProjectID,
		arg.ObjectID,
		arg.ChangesetID,
		arg.ParentVersionID,
		arg.IrVersion,
		arg.Path,
		arg.Body,
		arg.BodyHash,
		arg.CreatedBy,
	)
	var i ObjectVersion
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ObjectID,
		&i.Number,
		&i.State,
		&i.ChangesetID,
		&i.ParentVersionID,
		&i.SchemaVersion,
		&i.IrVersion,
		&i.Path,
		&i.Body,
		&i.BodyHash,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.CommittedAt,
	)
	return i, err
}

const getChangeset = `-- name: GetChangeset :one
SELECT id, project_id, kind, title, description, owner_id, state, risk, targets, seq, content_hash, has_conflicts, created_at, updated_at, submitted_at, merged_at FROM changesets WHERE id = $1 AND project_id = $2
`

type GetChangesetParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"projectId"`
}

func (q *Queries) GetChangeset(ctx context.Context, arg GetChangesetParams) (Changeset, error) {
	row := q.db.QueryRow(ctx, getChangeset, arg.ID, arg.ProjectID)
	var i Changeset
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Title,
		&i.Description,
		&i.OwnerID,
		&i.State,
		&i.Risk,
		&i.Targets,
		&i.Seq,
		&i.ContentHash,
		&i.HasConflicts,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubmittedAt,
		&i.MergedAt,
	)
	return i, err
}

const getChangesetObject = `-- name: GetChangesetObject :one
SELECT co.changeset_id, co.object_id, co.base_version_id, co.working_version_id, v.path AS working_path, v.body AS working_body
FROM changeset_objects co
JOIN object_versions v ON v.id = co.working_version_id
WHERE co.changeset_id = $1 AND co.object_id = $2
`

type GetChangesetObjectParams struct {
	ChangesetID uuid.UUID `json:"changesetId"`
	ObjectID    uuid.UUID `json:"objectId"`
}

type GetChangesetObjectRow struct {
	ChangesetID      uuid.UUID  `json:"changesetId"`
	ObjectID         uuid.UUID  `json:"objectId"`
	BaseVersionID    *uuid.UUID `json:"baseVersionId"`
	WorkingVersionID uuid.UUID  `json:"workingVersionId"`
	WorkingPath      *string    `json:"workingPath"`
	WorkingBody      []byte     `json:"workingBody"`
}

func (q *Queries) GetChangesetObject(ctx context.Context, arg GetChangesetObjectParams) (GetChangesetObjectRow, error) {
	row := q.db.QueryRow(ctx, getChangesetObject, arg.ChangesetID, arg.ObjectID)
	var i GetChangesetObjectRow
	err := row.Scan(
		&i.ChangesetID,
		&i.ObjectID,
		&i.BaseVersionID,
		&i.WorkingVersionID,
		&i.WorkingPath,
		&i.WorkingBody,
	)
	return i, err
}

const getHeadDocument = `-- name: GetHeadDocument :one
SELECT o.id, o.doc_kind, v.id AS version_id, v.state, v.path, v.body
FROM objects o
JOIN object_versions v ON v.id = o.head_version_id
WHERE o.id = $1 AND o.project_id = $2 AND o.kind = 'document' AND o.deleted_at IS NULL
`

type GetHeadDocumentParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"projectId"`
}

type GetHeadDocumentRow struct {
	ID        uuid.UUID `json:"id"`
	DocKind   *string   `json:"docKind"`
	VersionID uuid.UUID `json:"versionId"`
	State     string    `json:"state"`
	Path      *string   `json:"path"`
	Body      []byte    `json:"body"`
}

func (q *Queries) GetHeadDocument(ctx context.Context, arg GetHeadDocumentParams) (GetHeadDocumentRow, error) {
	row := q.db.QueryRow(ctx, getHeadDocument, arg.ID, arg.ProjectID)
	var i GetHeadDocumentRow
	err := row.Scan(
		&i.ID,
		&i.DocKind,
		&i.VersionID,
		&i.State,
		&i.Path,
		&i.Body,
	)
	return i, err
}

const getObject = `-- name: GetObject :one
SELECT id, project_id, kind, schema_name, doc_kind, head_version_id, head_path, created_at, deleted_at FROM objects WHERE id = $1 AND project_id = $2 AND deleted_at IS NULL
`

type GetObjectParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"projectId"`
}

func (q *Queries) GetObject(ctx context.Context, arg GetObjectParams) (Object, error) {
	row := q.db.QueryRow(ctx, getObject, arg.ID, arg.ProjectID)
	var i Object
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.SchemaName,
		&i.DocKind,
		&i.HeadVersionID,
		&i.HeadPath,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getVersion = `-- name: GetVersion :one
SELECT id, project_id, object_id, number, state, changeset_id, parent_version_id, schema_version, ir_version, path, body, body_hash, created_by, created_at, committed_at FROM object_versions WHERE id = $1
`

func (q *Queries) GetVersion(ctx context.Context, id uuid.UUID) (ObjectVersion, error) {
	row := q.db.QueryRow(ctx, getVersion, id)
	var i ObjectVersion
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ObjectID,
		&i.Number,
		&i.State,
		&i.ChangesetID,
		&i.ParentVersionID,
		&i.SchemaVersion,
		&i.IrVersion,
		&i.Path,
		&i.Body,
		&i.BodyHash,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.CommittedAt,
	)
	return i, err
}

const getWorkingDocument = `-- name: GetWorkingDocument :one
SELECT o.id, o.doc_kind, v.id AS version_id, v.state, v.path, v.body
FROM changeset_objects co
JOIN objects o ON o.id = co.object_id
JOIN object_versions v ON v.id = co.working_version_id
WHERE co.changeset_id = $1 AND co.object_id = $2 AND o.project_id = $3 AND o.kind = 'document'
`

type GetWorkingDocumentParams struct {
	ChangesetID uuid.UUID `json:"changesetId"`
	ObjectID    uuid.UUID `json:"objectId"`
	ProjectID   uuid.UUID `json:"projectId"`
}

type GetWorkingDocumentRow struct {
	ID        uuid.UUID `json:"id"`
	DocKind   *string   `json:"docKind"`
	VersionID uuid.UUID `json:"versionId"`
	State     string    `json:"state"`
	Path      *string   `json:"path"`
	Body      []byte    `json:"body"`
}

func (q *Queries) GetWorkingDocument(ctx context.Context, arg GetWorkingDocumentParams) (GetWorkingDocumentRow, error) {
	row := q.db.QueryRow(ctx, getWorkingDocument, arg.ChangesetID, arg.ObjectID, arg.ProjectID)
	var i GetWorkingDocumentRow
	err := row.Scan(
		&i.ID,
		&i.DocKind,
		&i.VersionID,
		&i.State,
		&i.Path,
		&i.Body,
	)
	return i, err
}

const insertOperation = `-- name: InsertOperation :one
INSERT INTO operations (id, project_id, changeset_id, seq, actor_id, source, target_object_id, type,
                        payload, before, after, inverse, reason, client_op_id, undo_of)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING id, project_id, changeset_id, seq, actor_id, on_behalf_of, source, target_object_id, type, payload, before, after, inverse, reason, client_op_id, undo_of, status, created_at
`

type InsertOperationParams struct {
	ID             uuid.UUID  `json:"id"`
	ProjectID      uuid.UUID  `json:"projectId"`
	ChangesetID    uuid.UUID  `json:"changesetId"`
	Seq            int32      `json:"seq"`
	ActorID        uuid.UUID  `json:"actorId"`
	Source         string     `json:"source"`
	TargetObjectID uuid.UUID  `json:"targetObjectId"`
	Type           string     `json:"type"`
	Payload        []byte     `json:"payload"`
	Before         []byte     `json:"before"`
	After          []byte     `json:"after"`
	Inverse        []byte     `json:"inverse"`
	Reason         *string    `json:"reason"`
	ClientOpID     *string    `json:"clientOpId"`
	UndoOf         *uuid.UUID `json:"undoOf"`
}

func (q *Queries) InsertOperation(ctx context.Context, arg InsertOperationParams) (Operation, error) {
	row := q.db.QueryRow(ctx, insertOperation,
		arg.ID,
		arg.ProjectID,
		arg.ChangesetID,
		arg.Seq,
		arg.ActorID,
		arg.Source,
		arg.TargetObjectID,
		arg.Type,
		arg.Payload,
		arg.Before,
		arg.After,
		arg.Inverse,
		arg.Reason,
		arg.ClientOpID,
		arg.UndoOf,
	)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ChangesetID,
		&i.Seq,
		&i.ActorID,
		&i.OnBehalfOf,
		&i.Source,
		&i.TargetObjectID,
		&i.Type,
		&i.Payload,
		&i.Before,
		&i.After,
		&i.Inverse,
		&i.Reason,
		&i.ClientOpID,
		&i.UndoOf,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const lastUndoableOperation = `-- name: LastUndoableOperation :one
SELECT o.id, o.project_id, o.changeset_id, o.seq, o.actor_id, o.on_behalf_of, o.source, o.target_object_id, o.type, o.payload, o.before, o.after, o.inverse, o.reason, o.client_op_id, o.undo_of, o.status, o.created_at FROM operations o
WHERE o.changeset_id = $1 AND o.undo_of IS NULL AND o.status = 'applied'
  AND NOT EXISTS (SELECT 1 FROM operations u WHERE u.undo_of = o.id)
ORDER BY o.seq DESC
LIMIT 1
`

// Последняя прямая (не отменяющая) операция, ещё не отменённая.
func (q *Queries) LastUndoableOperation(ctx context.Context, changesetID uuid.UUID) (Operation, error) {
	row := q.db.QueryRow(ctx, lastUndoableOperation, changesetID)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ChangesetID,
		&i.Seq,
		&i.ActorID,
		&i.OnBehalfOf,
		&i.Source,
		&i.TargetObjectID,
		&i.Type,
		&i.Payload,
		&i.Before,
		&i.After,
		&i.Inverse,
		&i.Reason,
		&i.ClientOpID,
		&i.UndoOf,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listChangesetObjects = `-- name: ListChangesetObjects :many
SELECT co.object_id, co.base_version_id, co.working_version_id, o.doc_kind
FROM changeset_objects co
JOIN objects o ON o.id = co.object_id
WHERE co.changeset_id = $1
ORDER BY co.object_id
`

type ListChangesetObjectsRow struct {
	ObjectID         uuid.UUID  `json:"objectId"`
	BaseVersionID    *uuid.UUID `json:"baseVersionId"`
	WorkingVersionID uuid.UUID  `json:"workingVersionId"`
	DocKind          *string    `json:"docKind"`
}

func (q *Queries) ListChangesetObjects(ctx context.Context, changesetID uuid.UUID) ([]ListChangesetObjectsRow, error) {
	rows, err := q.db.Query(ctx, listChangesetObjects, changesetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChangesetObjectsRow
	for rows.Next() {
		var i ListChangesetObjectsRow
		if err := rows.Scan(
			&i.ObjectID,
			&i.BaseVersionID,
			&i.WorkingVersionID,
			&i.DocKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChangesets = `-- name: ListChangesets :many
SELECT id, project_id, kind, title, description, owner_id, state, risk, targets, seq, content_hash, has_conflicts, created_at, updated_at, submitted_at, merged_at FROM changesets
WHERE project_id = $1 AND ($2::text IS NULL OR state = $2)
ORDER BY created_at DESC, id DESC
LIMIT 100
`

type ListChangesetsParams struct {
	ProjectID uuid.UUID `json:"projectId"`
	State     *string   `json:"state"`
}

func (q *Queries) ListChangesets(ctx context.Context, arg ListChangesetsParams) ([]Changeset, error) {
	rows, err := q.db.Query(ctx, listChangesets, arg.ProjectID, arg.State)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Changeset
	for rows.Next() {
		var i Changeset
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Kind,
			&i.Title,
			&i.Description,
			&i.OwnerID,
			&i.State,
			&i.Risk,
			&i.Targets,
			&i.Seq,
			&i.ContentHash,
			&i.HasConflicts,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SubmittedAt,
			&i.MergedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOperations = `-- name: ListOperations :many
SELECT id, project_id, changeset_id, seq, actor_id, on_behalf_of, source, target_object_id, type, payload, before, after, inverse, reason, client_op_id, undo_of, status, created_at FROM operations WHERE changeset_id = $1 AND seq > $2 ORDER BY seq LIMIT 500
`

type ListOperationsParams struct {
	ChangesetID uuid.UUID `json:"changesetId"`
	Seq         int32     `json:"seq"`
}

func (q *Queries) ListOperations(ctx context.Context, arg ListOperationsParams) ([]Operation, error) {
	rows, err := q.db.Query(ctx, listOperations, arg.ChangesetID, arg.Seq)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Operation
	for rows.Next() {
		var i Operation
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ChangesetID,
			&i.Seq,
			&i.ActorID,
			&i.OnBehalfOf,
			&i.Source,
			&i.TargetObjectID,
			&i.Type,
			&i.Payload,
			&i.Before,
			&i.After,
			&i.Inverse,
			&i.Reason,
			&i.ClientOpID,
			&i.UndoOf,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockChangeset = `-- name: LockChangeset :one
SELECT id, project_id, kind, title, description, owner_id, state, risk, targets, seq, content_hash, has_conflicts, created_at, updated_at, submitted_at, merged_at FROM changesets WHERE id = $1 AND project_id = $2 FOR UPDATE
`

type LockChangesetParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"projectId"`
}

func (q *Queries) LockChangeset(ctx context.Context, arg LockChangesetParams) (Changeset, error) {
	row := q.db.QueryRow(ctx, lockChangeset, arg.ID, arg.ProjectID)
	var i Changeset
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Title,
		&i.Description,
		&i.OwnerID,
		&i.State,
		&i.Risk,
		&i.Targets,
		&i.Seq,
		&i.ContentHash,
		&i.HasConflicts,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubmittedAt,
		&i.MergedAt,
	)
	return i, err
}

const routeTaken = `-- name: RouteTaken :one
SELECT id FROM objects
WHERE project_id = $1 AND id <> $2 AND deleted_at IS NULL AND head_path IS NOT NULL
  AND route_shape(head_path) = route_shape($3::text)
LIMIT 1
`

type RouteTakenParams struct {
	ProjectID uuid.UUID `json:"projectId"`
	ID        uuid.UUID `json:"id"`
	Path      string    `json:"path"`
}

// Объект, чей head уже занимает маршрут той же формы (route_shape), кроме данного.
func (q *Queries) RouteTaken(ctx context.Context, arg RouteTakenParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, routeTaken, arg.ProjectID, arg.ID, arg.Path)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const setChangesetSeq = `-- name: SetChangesetSeq :exec
UPDATE changesets SET seq = $2, updated_at = now() WHERE id = $1
`

type SetChangesetSeqParams struct {
	ID  uuid.UUID `json:"id"`
	Seq int32     `json:"seq"`
}

func (q *Queries) SetChangesetSeq(ctx context.Context, arg SetChangesetSeqParams) error {
	_, err := q.db.Exec(ctx, setChangesetSeq, arg.ID, arg.Seq)
	return err
}

const setChangesetState = `-- name: SetChangesetState :exec
UPDATE changesets SET state = $2, updated_at = now() WHERE id = $1
`

type SetChangesetStateParams struct {
	ID    uuid.UUID `json:"id"`
	State string    `json:"state"`
}

func (q *Queries) SetChangesetState(ctx context.Context, arg SetChangesetStateParams) error {
	_, err := q.db.Exec(ctx, setChangesetState, arg.ID, arg.State)
	return err
}

const updateWorkingVersion = `-- name: UpdateWorkingVersion :exec
UPDATE object_versions SET path = $2, body = $3, body_hash = $4 WHERE id = $1 AND state = 'working'
`

type UpdateWorkingVersionParams struct {
	ID       uuid.UUID `json:"id"`
	Path     *string   `json:"path"`
	Body     []byte    `json:"body"`
	BodyHash []byte    `json:"bodyHash"`
}

func (q *Queries) UpdateWorkingVersion(ctx context.Context, arg UpdateWorkingVersionParams) error {
	_, err := q.db.Exec(ctx, updateWorkingVersion,
		arg.ID,
		arg.Path,
		arg.Body,
		arg.BodyHash,
	)
	return err
}
