// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: content.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const contentHeads = `-- name: ContentHeads :many
SELECT o.id, o.kind, o.schema_name, v.body, v.deleted FROM objects o
JOIN object_versions v ON v.id=o.head_version_id WHERE o.project_id=$1 AND o.kind='entity' ORDER BY o.id
`

type ContentHeadsRow struct {
	ID         uuid.UUID `json:"id"`
	Kind       string    `json:"kind"`
	SchemaName *string   `json:"schemaName"`
	Body       []byte    `json:"body"`
	Deleted    bool      `json:"deleted"`
}

func (q *Queries) ContentHeads(ctx context.Context, projectID uuid.UUID) ([]ContentHeadsRow, error) {
	rows, err := q.db.Query(ctx, contentHeads, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContentHeadsRow
	for rows.Next() {
		var i ContentHeadsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.SchemaName,
			&i.Body,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const contentIdentity = `-- name: ContentIdentity :one
SELECT id, project_id, kind, schema_name, doc_kind, head_version_id, head_path, created_at, deleted_at FROM objects WHERE project_id=$1 AND id=$2
`

type ContentIdentityParams struct {
	ProjectID uuid.UUID `json:"projectId"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) ContentIdentity(ctx context.Context, arg ContentIdentityParams) (Object, error) {
	row := q.db.QueryRow(ctx, contentIdentity, arg.ProjectID, arg.ID)
	var i Object
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.SchemaName,
		&i.DocKind,
		&i.HeadVersionID,
		&i.HeadPath,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const contentVersion = `-- name: ContentVersion :one
SELECT v.id, v.project_id, v.object_id, v.number, v.state, v.changeset_id, v.parent_version_id, v.schema_version, v.ir_version, v.path, v.body, v.body_hash, v.created_by, v.created_at, v.committed_at, v.certified, v.deleted, o.kind, o.schema_name FROM objects o JOIN object_versions v ON v.object_id=o.id
WHERE o.project_id=$1 AND o.id=$2
AND v.id=COALESCE(
 (SELECT co.working_version_id FROM changeset_objects co WHERE co.object_id=o.id AND co.changeset_id=$3::uuid),
 CASE WHEN $4::boolean THEN o.head_version_id ELSE
 (SELECT pp.version_id FROM published_pointers pp WHERE pp.object_id=o.id AND pp.environment_id=$5) END)
`

type ContentVersionParams struct {
	ProjectID     uuid.UUID  `json:"projectId"`
	ObjectID      uuid.UUID  `json:"objectId"`
	ChangesetID   *uuid.UUID `json:"changesetId"`
	UseHead       bool       `json:"useHead"`
	EnvironmentID uuid.UUID  `json:"environmentId"`
}

type ContentVersionRow struct {
	ID              uuid.UUID  `json:"id"`
	ProjectID       uuid.UUID  `json:"projectId"`
	ObjectID        uuid.UUID  `json:"objectId"`
	Number          *int32     `json:"number"`
	State           string     `json:"state"`
	ChangesetID     *uuid.UUID `json:"changesetId"`
	ParentVersionID *uuid.UUID `json:"parentVersionId"`
	SchemaVersion   *int32     `json:"schemaVersion"`
	IrVersion       *string    `json:"irVersion"`
	Path            *string    `json:"path"`
	Body            []byte     `json:"body"`
	BodyHash        []byte     `json:"bodyHash"`
	CreatedBy       uuid.UUID  `json:"createdBy"`
	CreatedAt       time.Time  `json:"createdAt"`
	CommittedAt     *time.Time `json:"committedAt"`
	Certified       bool       `json:"certified"`
	Deleted         bool       `json:"deleted"`
	Kind            string     `json:"kind"`
	SchemaName      *string    `json:"schemaName"`
}

func (q *Queries) ContentVersion(ctx context.Context, arg ContentVersionParams) (ContentVersionRow, error) {
	row := q.db.QueryRow(ctx, contentVersion,
		arg.ProjectID,
		arg.ObjectID,
		arg.ChangesetID,
		arg.UseHead,
		arg.EnvironmentID,
	)
	var i ContentVersionRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ObjectID,
		&i.Number,
		&i.State,
		&i.ChangesetID,
		&i.ParentVersionID,
		&i.SchemaVersion,
		&i.IrVersion,
		&i.Path,
		&i.Body,
		&i.BodyHash,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.CommittedAt,
		&i.Certified,
		&i.Deleted,
		&i.Kind,
		&i.SchemaName,
	)
	return i, err
}

const createEntityObject = `-- name: CreateEntityObject :one
INSERT INTO objects (id, project_id, kind, schema_name) VALUES ($1,$2,'entity',$3) RETURNING id, project_id, kind, schema_name, doc_kind, head_version_id, head_path, created_at, deleted_at
`

type CreateEntityObjectParams struct {
	ID         uuid.UUID `json:"id"`
	ProjectID  uuid.UUID `json:"projectId"`
	SchemaName *string   `json:"schemaName"`
}

func (q *Queries) CreateEntityObject(ctx context.Context, arg CreateEntityObjectParams) (Object, error) {
	row := q.db.QueryRow(ctx, createEntityObject, arg.ID, arg.ProjectID, arg.SchemaName)
	var i Object
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.SchemaName,
		&i.DocKind,
		&i.HeadVersionID,
		&i.HeadPath,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const setContentTargets = `-- name: SetContentTargets :exec
UPDATE changesets SET targets=$2 WHERE id=$1
`

type SetContentTargetsParams struct {
	ID      uuid.UUID `json:"id"`
	Targets []string  `json:"targets"`
}

func (q *Queries) SetContentTargets(ctx context.Context, arg SetContentTargetsParams) error {
	_, err := q.db.Exec(ctx, setContentTargets, arg.ID, arg.Targets)
	return err
}

const setWorkingContent = `-- name: SetWorkingContent :exec
UPDATE object_versions SET ir_version=NULL, schema_version=$2, deleted=$3 WHERE id=$1 AND state='working'
`

type SetWorkingContentParams struct {
	ID            uuid.UUID `json:"id"`
	SchemaVersion *int32    `json:"schemaVersion"`
	Deleted       bool      `json:"deleted"`
}

func (q *Queries) SetWorkingContent(ctx context.Context, arg SetWorkingContentParams) error {
	_, err := q.db.Exec(ctx, setWorkingContent, arg.ID, arg.SchemaVersion, arg.Deleted)
	return err
}
