// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delivery.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const authenticateDeliveryKey = `-- name: AuthenticateDeliveryKey :one
SELECT k.project_id, k.environment_id, p.slug AS project_slug, e.name AS environment_name
FROM delivery_keys k
JOIN projects p ON p.id = k.project_id
JOIN environments e ON e.id = k.environment_id
WHERE k.token_hash = $1 AND k.revoked_at IS NULL
`

type AuthenticateDeliveryKeyRow struct {
	ProjectID       uuid.UUID `json:"projectId"`
	EnvironmentID   uuid.UUID `json:"environmentId"`
	ProjectSlug     string    `json:"projectSlug"`
	EnvironmentName string    `json:"environmentName"`
}

func (q *Queries) AuthenticateDeliveryKey(ctx context.Context, tokenHash []byte) (AuthenticateDeliveryKeyRow, error) {
	row := q.db.QueryRow(ctx, authenticateDeliveryKey, tokenHash)
	var i AuthenticateDeliveryKeyRow
	err := row.Scan(
		&i.ProjectID,
		&i.EnvironmentID,
		&i.ProjectSlug,
		&i.EnvironmentName,
	)
	return i, err
}

const createDeliveryKey = `-- name: CreateDeliveryKey :one
INSERT INTO delivery_keys (id, project_id, environment_id, name, token_hash, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, environment_id, name, token_hash, created_by, created_at, revoked_at
`

type CreateDeliveryKeyParams struct {
	ID            uuid.UUID `json:"id"`
	ProjectID     uuid.UUID `json:"projectId"`
	EnvironmentID uuid.UUID `json:"environmentId"`
	Name          string    `json:"name"`
	TokenHash     []byte    `json:"tokenHash"`
	CreatedBy     uuid.UUID `json:"createdBy"`
}

func (q *Queries) CreateDeliveryKey(ctx context.Context, arg CreateDeliveryKeyParams) (DeliveryKey, error) {
	row := q.db.QueryRow(ctx, createDeliveryKey,
		arg.ID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.Name,
		arg.TokenHash,
		arg.CreatedBy,
	)
	var i DeliveryKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.Name,
		&i.TokenHash,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getDeliveredDocument = `-- name: GetDeliveredDocument :one
SELECT o.id, o.doc_kind, v.id AS version_id, v.path, v.body
FROM published_pointers pp
JOIN objects o ON o.id = pp.object_id
JOIN object_versions v ON v.id = pp.version_id
WHERE pp.environment_id = $1 AND pp.object_id = $2 AND o.kind = 'document'
`

type GetDeliveredDocumentParams struct {
	EnvironmentID uuid.UUID `json:"environmentId"`
	ObjectID      uuid.UUID `json:"objectId"`
}

type GetDeliveredDocumentRow struct {
	ID        uuid.UUID `json:"id"`
	DocKind   *string   `json:"docKind"`
	VersionID uuid.UUID `json:"versionId"`
	Path      *string   `json:"path"`
	Body      []byte    `json:"body"`
}

// Опубликованная в окружении версия документа.
func (q *Queries) GetDeliveredDocument(ctx context.Context, arg GetDeliveredDocumentParams) (GetDeliveredDocumentRow, error) {
	row := q.db.QueryRow(ctx, getDeliveredDocument, arg.EnvironmentID, arg.ObjectID)
	var i GetDeliveredDocumentRow
	err := row.Scan(
		&i.ID,
		&i.DocKind,
		&i.VersionID,
		&i.Path,
		&i.Body,
	)
	return i, err
}

const getEnvironmentPreviewKey = `-- name: GetEnvironmentPreviewKey :one
SELECT e.id, e.name, e.preview_key, p.id AS project_id, p.slug AS project_slug
FROM environments e JOIN projects p ON p.id = e.project_id
WHERE p.slug = $1 AND e.name = $2
`

type GetEnvironmentPreviewKeyParams struct {
	Slug string `json:"slug"`
	Name string `json:"name"`
}

type GetEnvironmentPreviewKeyRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	PreviewKey  []byte    `json:"previewKey"`
	ProjectID   uuid.UUID `json:"projectId"`
	ProjectSlug string    `json:"projectSlug"`
}

func (q *Queries) GetEnvironmentPreviewKey(ctx context.Context, arg GetEnvironmentPreviewKeyParams) (GetEnvironmentPreviewKeyRow, error) {
	row := q.db.QueryRow(ctx, getEnvironmentPreviewKey, arg.Slug, arg.Name)
	var i GetEnvironmentPreviewKeyRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PreviewKey,
		&i.ProjectID,
		&i.ProjectSlug,
	)
	return i, err
}

const listDeliveryKeys = `-- name: ListDeliveryKeys :many
SELECT k.id, k.name, k.created_by, k.created_at, k.revoked_at, e.name AS environment_name
FROM delivery_keys k JOIN environments e ON e.id = k.environment_id
WHERE k.project_id = $1
ORDER BY k.created_at, k.id
`

type ListDeliveryKeysRow struct {
	ID              uuid.UUID  `json:"id"`
	Name            string     `json:"name"`
	CreatedBy       uuid.UUID  `json:"createdBy"`
	CreatedAt       time.Time  `json:"createdAt"`
	RevokedAt       *time.Time `json:"revokedAt"`
	EnvironmentName string     `json:"environmentName"`
}

func (q *Queries) ListDeliveryKeys(ctx context.Context, projectID uuid.UUID) ([]ListDeliveryKeysRow, error) {
	rows, err := q.db.Query(ctx, listDeliveryKeys, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDeliveryKeysRow
	for rows.Next() {
		var i ListDeliveryKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.RevokedAt,
			&i.EnvironmentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDraftRoutes = `-- name: ListDraftRoutes :many
WITH ws AS (
  SELECT co.object_id, v.id AS version_id, v.path
  FROM changeset_objects co JOIN object_versions v ON v.id = co.working_version_id
  WHERE co.changeset_id = $1::uuid
)
SELECT ws.path::text AS path, ws.object_id, ws.version_id FROM ws WHERE ws.path IS NOT NULL
UNION ALL
SELECT o.head_path::text, o.id, o.head_version_id::uuid
FROM objects o
WHERE o.project_id = $2 AND o.head_path IS NOT NULL AND o.deleted_at IS NULL
  AND o.id NOT IN (SELECT object_id FROM ws)
ORDER BY 1
`

type ListDraftRoutesParams struct {
	ChangesetID *uuid.UUID `json:"changesetId"`
	ProjectID   uuid.UUID  `json:"projectId"`
}

type ListDraftRoutesRow struct {
	Path      string    `json:"path"`
	ObjectID  uuid.UUID `json:"objectId"`
	VersionID uuid.UUID `json:"versionId"`
}

// Маршруты чернового режима (API-040): объекты Change Set — из рабочих версий, остальные — из head.
func (q *Queries) ListDraftRoutes(ctx context.Context, arg ListDraftRoutesParams) ([]ListDraftRoutesRow, error) {
	rows, err := q.db.Query(ctx, listDraftRoutes, arg.ChangesetID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDraftRoutesRow
	for rows.Next() {
		var i ListDraftRoutesRow
		if err := rows.Scan(&i.Path, &i.ObjectID, &i.VersionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeDeliveryKey = `-- name: RevokeDeliveryKey :one
UPDATE delivery_keys k SET revoked_at = now()
FROM environments e
WHERE k.id = $1 AND k.project_id = $2 AND k.revoked_at IS NULL AND e.id = k.environment_id
RETURNING k.id, k.name, k.created_by, k.created_at, k.revoked_at, e.name AS environment_name
`

type RevokeDeliveryKeyParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"projectId"`
}

type RevokeDeliveryKeyRow struct {
	ID              uuid.UUID  `json:"id"`
	Name            string     `json:"name"`
	CreatedBy       uuid.UUID  `json:"createdBy"`
	CreatedAt       time.Time  `json:"createdAt"`
	RevokedAt       *time.Time `json:"revokedAt"`
	EnvironmentName string     `json:"environmentName"`
}

func (q *Queries) RevokeDeliveryKey(ctx context.Context, arg RevokeDeliveryKeyParams) (RevokeDeliveryKeyRow, error) {
	row := q.db.QueryRow(ctx, revokeDeliveryKey, arg.ID, arg.ProjectID)
	var i RevokeDeliveryKeyRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.EnvironmentName,
	)
	return i, err
}
