// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT actor_id, key, command, request_hash, status, response, created_at FROM idempotency_keys
WHERE actor_id = $1 AND key = $2 AND created_at > now() - interval '24 hours'
`

type GetIdempotencyKeyParams struct {
	ActorID uuid.UUID `json:"actorId"`
	Key     string    `json:"key"`
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.ActorID, arg.Key)
	var i IdempotencyKey
	err := row.Scan(
		&i.ActorID,
		&i.Key,
		&i.Command,
		&i.RequestHash,
		&i.Status,
		&i.Response,
		&i.CreatedAt,
	)
	return i, err
}

const lockIdempotencyKey = `-- name: LockIdempotencyKey :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text || ':' || $2::text, 0))
`

type LockIdempotencyKeyParams struct {
	ActorID string `json:"actorId"`
	Key     string `json:"key"`
}

// Сериализует параллельные запросы с одним ключом до конца транзакции.
func (q *Queries) LockIdempotencyKey(ctx context.Context, arg LockIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, lockIdempotencyKey, arg.ActorID, arg.Key)
	return err
}

const saveIdempotencyKey = `-- name: SaveIdempotencyKey :exec
INSERT INTO idempotency_keys (actor_id, key, command, request_hash, status, response)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (actor_id, key) DO UPDATE
SET command = EXCLUDED.command, request_hash = EXCLUDED.request_hash,
    status = EXCLUDED.status, response = EXCLUDED.response, created_at = now()
`

type SaveIdempotencyKeyParams struct {
	ActorID     uuid.UUID `json:"actorId"`
	Key         string    `json:"key"`
	Command     string    `json:"command"`
	RequestHash []byte    `json:"requestHash"`
	Status      int32     `json:"status"`
	Response    []byte    `json:"response"`
}

func (q *Queries) SaveIdempotencyKey(ctx context.Context, arg SaveIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, saveIdempotencyKey,
		arg.ActorID,
		arg.Key,
		arg.Command,
		arg.RequestHash,
		arg.Status,
		arg.Response,
	)
	return err
}
