// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: manifests.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const bindManifestCandidate = `-- name: BindManifestCandidate :exec
INSERT INTO changeset_manifest_candidates (changeset_id, project_id, environment_id, manifest_id, base_manifest_id)
VALUES ($1, $2, $3, $4, $5)
`

type BindManifestCandidateParams struct {
	ChangesetID    uuid.UUID  `json:"changesetId"`
	ProjectID      uuid.UUID  `json:"projectId"`
	EnvironmentID  uuid.UUID  `json:"environmentId"`
	ManifestID     uuid.UUID  `json:"manifestId"`
	BaseManifestID *uuid.UUID `json:"baseManifestId"`
}

func (q *Queries) BindManifestCandidate(ctx context.Context, arg BindManifestCandidateParams) error {
	_, err := q.db.Exec(ctx, bindManifestCandidate,
		arg.ChangesetID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.ManifestID,
		arg.BaseManifestID,
	)
	return err
}

const changesetManifestDiagnostics = `-- name: ChangesetManifestDiagnostics :many
SELECT e.name AS environment, m.hash AS manifest_hash, d.diagnostics, d.checked_at,
(d.checked_seq IS NULL OR d.stale OR d.checked_seq <> cs.seq
 OR d.manifest_id IS DISTINCT FROM COALESCE(b.manifest_id,e.active_manifest_id)
 OR (b.changeset_id IS NOT NULL AND b.base_manifest_id IS DISTINCT FROM e.active_manifest_id))::boolean AS stale
FROM changesets cs JOIN environments e ON e.project_id = cs.project_id
LEFT JOIN changeset_manifest_candidates b ON b.changeset_id = cs.id AND b.environment_id = e.id
LEFT JOIN changeset_manifest_diagnostics d ON d.changeset_id = cs.id AND d.environment_id = e.id
LEFT JOIN manifests m ON m.id = d.manifest_id
WHERE cs.project_id = $1 AND cs.id = $2
AND (cardinality(cs.targets) = 0 OR e.name = ANY(cs.targets))
AND (cs.kind <> 'schema' OR b.changeset_id IS NOT NULL) ORDER BY e.name
`

type ChangesetManifestDiagnosticsParams struct {
	ProjectID uuid.UUID `json:"projectId"`
	ID        uuid.UUID `json:"id"`
}

type ChangesetManifestDiagnosticsRow struct {
	Environment  string     `json:"environment"`
	ManifestHash *string    `json:"manifestHash"`
	Diagnostics  []byte     `json:"diagnostics"`
	CheckedAt    *time.Time `json:"checkedAt"`
	Stale        bool       `json:"stale"`
}

func (q *Queries) ChangesetManifestDiagnostics(ctx context.Context, arg ChangesetManifestDiagnosticsParams) ([]ChangesetManifestDiagnosticsRow, error) {
	rows, err := q.db.Query(ctx, changesetManifestDiagnostics, arg.ProjectID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChangesetManifestDiagnosticsRow
	for rows.Next() {
		var i ChangesetManifestDiagnosticsRow
		if err := rows.Scan(
			&i.Environment,
			&i.ManifestHash,
			&i.Diagnostics,
			&i.CheckedAt,
			&i.Stale,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createManifestCandidate = `-- name: CreateManifestCandidate :one
INSERT INTO changesets (id, project_id, kind, title, owner_id, state, targets)
VALUES ($1, $2, 'schema', $3, $4, 'open', $5) RETURNING id, project_id, kind, title, description, owner_id, state, risk, targets, seq, content_hash, has_conflicts, created_at, updated_at, submitted_at, merged_at
`

type CreateManifestCandidateParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"projectId"`
	Title     string    `json:"title"`
	OwnerID   uuid.UUID `json:"ownerId"`
	Targets   []string  `json:"targets"`
}

func (q *Queries) CreateManifestCandidate(ctx context.Context, arg CreateManifestCandidateParams) (Changeset, error) {
	row := q.db.QueryRow(ctx, createManifestCandidate,
		arg.ID,
		arg.ProjectID,
		arg.Title,
		arg.OwnerID,
		arg.Targets,
	)
	var i Changeset
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Title,
		&i.Description,
		&i.OwnerID,
		&i.State,
		&i.Risk,
		&i.Targets,
		&i.Seq,
		&i.ContentHash,
		&i.HasConflicts,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubmittedAt,
		&i.MergedAt,
	)
	return i, err
}

const getManifestByHash = `-- name: GetManifestByHash :one
SELECT id, project_id, hash, app_version, body, code_index_key, registered_by, created_at FROM manifests WHERE project_id = $1 AND hash = $2
`

type GetManifestByHashParams struct {
	ProjectID uuid.UUID `json:"projectId"`
	Hash      string    `json:"hash"`
}

func (q *Queries) GetManifestByHash(ctx context.Context, arg GetManifestByHashParams) (Manifest, error) {
	row := q.db.QueryRow(ctx, getManifestByHash, arg.ProjectID, arg.Hash)
	var i Manifest
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Hash,
		&i.AppVersion,
		&i.Body,
		&i.CodeIndexKey,
		&i.RegisteredBy,
		&i.CreatedAt,
	)
	return i, err
}

const getManifestByID = `-- name: GetManifestByID :one
SELECT id, project_id, hash, app_version, body, code_index_key, registered_by, created_at FROM manifests WHERE project_id = $1 AND id = $2
`

type GetManifestByIDParams struct {
	ProjectID uuid.UUID `json:"projectId"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) GetManifestByID(ctx context.Context, arg GetManifestByIDParams) (Manifest, error) {
	row := q.db.QueryRow(ctx, getManifestByID, arg.ProjectID, arg.ID)
	var i Manifest
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Hash,
		&i.AppVersion,
		&i.Body,
		&i.CodeIndexKey,
		&i.RegisteredBy,
		&i.CreatedAt,
	)
	return i, err
}

const getManifestEnvironment = `-- name: GetManifestEnvironment :one
SELECT id, project_id, name, kind, active_manifest_id, app_url, expires_at, created_at, preview_key FROM environments WHERE project_id = $1 AND name = $2
`

type GetManifestEnvironmentParams struct {
	ProjectID uuid.UUID `json:"projectId"`
	Name      string    `json:"name"`
}

func (q *Queries) GetManifestEnvironment(ctx context.Context, arg GetManifestEnvironmentParams) (Environment, error) {
	row := q.db.QueryRow(ctx, getManifestEnvironment, arg.ProjectID, arg.Name)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Kind,
		&i.ActiveManifestID,
		&i.AppUrl,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.PreviewKey,
	)
	return i, err
}

const getStandardSchemaVersion = `-- name: GetStandardSchemaVersion :one
SELECT project_id, schema_name, version, body, manifest_id, created_at FROM schema_versions WHERE project_id = $1 AND schema_name = $2 AND version = $3
`

type GetStandardSchemaVersionParams struct {
	ProjectID  uuid.UUID `json:"projectId"`
	SchemaName string    `json:"schemaName"`
	Version    int32     `json:"version"`
}

func (q *Queries) GetStandardSchemaVersion(ctx context.Context, arg GetStandardSchemaVersionParams) (SchemaVersion, error) {
	row := q.db.QueryRow(ctx, getStandardSchemaVersion, arg.ProjectID, arg.SchemaName, arg.Version)
	var i SchemaVersion
	err := row.Scan(
		&i.ProjectID,
		&i.SchemaName,
		&i.Version,
		&i.Body,
		&i.ManifestID,
		&i.CreatedAt,
	)
	return i, err
}

const insertManifest = `-- name: InsertManifest :exec
INSERT INTO manifests (id, project_id, hash, app_version, body, code_index_key, registered_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (project_id, hash) DO NOTHING
`

type InsertManifestParams struct {
	ID           uuid.UUID `json:"id"`
	ProjectID    uuid.UUID `json:"projectId"`
	Hash         string    `json:"hash"`
	AppVersion   string    `json:"appVersion"`
	Body         []byte    `json:"body"`
	CodeIndexKey *string   `json:"codeIndexKey"`
	RegisteredBy uuid.UUID `json:"registeredBy"`
}

// Повтор hash не изменяет исходные тело, автора, время и code index (MF-002).
func (q *Queries) InsertManifest(ctx context.Context, arg InsertManifestParams) error {
	_, err := q.db.Exec(ctx, insertManifest,
		arg.ID,
		arg.ProjectID,
		arg.Hash,
		arg.AppVersion,
		arg.Body,
		arg.CodeIndexKey,
		arg.RegisteredBy,
	)
	return err
}

const insertPreviewSchemaSnapshot = `-- name: InsertPreviewSchemaSnapshot :exec
INSERT INTO preview_schema_snapshots (manifest_id, schema_name, version, body)
VALUES ($1, $2, $3, $4) ON CONFLICT (manifest_id, schema_name) DO NOTHING
`

type InsertPreviewSchemaSnapshotParams struct {
	ManifestID uuid.UUID `json:"manifestId"`
	SchemaName string    `json:"schemaName"`
	Version    int32     `json:"version"`
	Body       []byte    `json:"body"`
}

func (q *Queries) InsertPreviewSchemaSnapshot(ctx context.Context, arg InsertPreviewSchemaSnapshotParams) error {
	_, err := q.db.Exec(ctx, insertPreviewSchemaSnapshot,
		arg.ManifestID,
		arg.SchemaName,
		arg.Version,
		arg.Body,
	)
	return err
}

const insertStandardSchemaVersion = `-- name: InsertStandardSchemaVersion :exec
INSERT INTO schema_versions (project_id, schema_name, version, body, manifest_id)
VALUES ($1, $2, $3, $4, $5)
`

type InsertStandardSchemaVersionParams struct {
	ProjectID  uuid.UUID `json:"projectId"`
	SchemaName string    `json:"schemaName"`
	Version    int32     `json:"version"`
	Body       []byte    `json:"body"`
	ManifestID uuid.UUID `json:"manifestId"`
}

func (q *Queries) InsertStandardSchemaVersion(ctx context.Context, arg InsertStandardSchemaVersionParams) error {
	_, err := q.db.Exec(ctx, insertStandardSchemaVersion,
		arg.ProjectID,
		arg.SchemaName,
		arg.Version,
		arg.Body,
		arg.ManifestID,
	)
	return err
}

const latestStandardSchemaVersion = `-- name: LatestStandardSchemaVersion :one
SELECT project_id, schema_name, version, body, manifest_id, created_at FROM schema_versions WHERE project_id = $1 AND schema_name = $2 ORDER BY version DESC LIMIT 1
`

type LatestStandardSchemaVersionParams struct {
	ProjectID  uuid.UUID `json:"projectId"`
	SchemaName string    `json:"schemaName"`
}

func (q *Queries) LatestStandardSchemaVersion(ctx context.Context, arg LatestStandardSchemaVersionParams) (SchemaVersion, error) {
	row := q.db.QueryRow(ctx, latestStandardSchemaVersion, arg.ProjectID, arg.SchemaName)
	var i SchemaVersion
	err := row.Scan(
		&i.ProjectID,
		&i.SchemaName,
		&i.Version,
		&i.Body,
		&i.ManifestID,
		&i.CreatedAt,
	)
	return i, err
}

const listPreviewSchemaSnapshots = `-- name: ListPreviewSchemaSnapshots :many
SELECT s.manifest_id, s.schema_name, s.version, s.body FROM preview_schema_snapshots s JOIN manifests m ON m.id = s.manifest_id
WHERE m.project_id = $1 AND s.manifest_id = $2 ORDER BY s.schema_name
`

type ListPreviewSchemaSnapshotsParams struct {
	ProjectID  uuid.UUID `json:"projectId"`
	ManifestID uuid.UUID `json:"manifestId"`
}

func (q *Queries) ListPreviewSchemaSnapshots(ctx context.Context, arg ListPreviewSchemaSnapshotsParams) ([]PreviewSchemaSnapshot, error) {
	rows, err := q.db.Query(ctx, listPreviewSchemaSnapshots, arg.ProjectID, arg.ManifestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PreviewSchemaSnapshot
	for rows.Next() {
		var i PreviewSchemaSnapshot
		if err := rows.Scan(
			&i.ManifestID,
			&i.SchemaName,
			&i.Version,
			&i.Body,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockManifestEnvironment = `-- name: LockManifestEnvironment :one
SELECT id, project_id, name, kind, active_manifest_id, app_url, expires_at, created_at, preview_key FROM environments WHERE project_id = $1 AND name = $2 FOR UPDATE
`

type LockManifestEnvironmentParams struct {
	ProjectID uuid.UUID `json:"projectId"`
	Name      string    `json:"name"`
}

func (q *Queries) LockManifestEnvironment(ctx context.Context, arg LockManifestEnvironmentParams) (Environment, error) {
	row := q.db.QueryRow(ctx, lockManifestEnvironment, arg.ProjectID, arg.Name)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Kind,
		&i.ActiveManifestID,
		&i.AppUrl,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.PreviewKey,
	)
	return i, err
}

const manifestChangesets = `-- name: ManifestChangesets :many
SELECT id, project_id, kind, title, description, owner_id, state, risk, targets, seq, content_hash, has_conflicts, created_at, updated_at, submitted_at, merged_at FROM changesets WHERE project_id = $1 AND state NOT IN ('merged', 'abandoned')
AND (cardinality(targets) = 0 OR $2::text = ANY(targets)) ORDER BY id FOR UPDATE
`

type ManifestChangesetsParams struct {
	ProjectID   uuid.UUID `json:"projectId"`
	Environment string    `json:"environment"`
}

func (q *Queries) ManifestChangesets(ctx context.Context, arg ManifestChangesetsParams) ([]Changeset, error) {
	rows, err := q.db.Query(ctx, manifestChangesets, arg.ProjectID, arg.Environment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Changeset
	for rows.Next() {
		var i Changeset
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Kind,
			&i.Title,
			&i.Description,
			&i.OwnerID,
			&i.State,
			&i.Risk,
			&i.Targets,
			&i.Seq,
			&i.ContentHash,
			&i.HasConflicts,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SubmittedAt,
			&i.MergedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const manifestImpactVersions = `-- name: ManifestImpactVersions :many
WITH target_environment AS (
 SELECT env.id FROM environments env WHERE env.project_id = $1::uuid AND env.name = $2::text
)
SELECT o.id AS object_id, v.id AS version_id, v.body, v.path, v.certified, 'head'::text AS stage, NULL::uuid AS changeset_id
FROM objects o JOIN object_versions v ON v.id = o.head_version_id AND v.object_id = o.id
CROSS JOIN target_environment e
WHERE o.project_id = $1 AND o.kind = 'document' AND o.deleted_at IS NULL
UNION ALL
SELECT o.id, v.id, v.body, v.path, v.certified, 'published'::text, NULL::uuid
FROM target_environment e JOIN published_pointers pp ON pp.environment_id = e.id
JOIN objects o ON o.id = pp.object_id
JOIN object_versions v ON v.id = pp.version_id AND v.object_id = o.id
WHERE o.project_id = $1 AND o.kind = 'document'
UNION ALL
SELECT o.id, v.id, v.body, v.path, v.certified, 'working'::text, cs.id
FROM changesets cs JOIN changeset_objects co ON co.changeset_id = cs.id
JOIN objects o ON o.id = co.object_id
JOIN object_versions v ON v.id = co.working_version_id AND v.object_id = o.id
CROSS JOIN target_environment e
WHERE cs.project_id = $1 AND o.project_id = $1
  AND o.kind = 'document' AND cs.state NOT IN ('merged', 'abandoned')
ORDER BY object_id, stage, version_id, changeset_id
`

type ManifestImpactVersionsParams struct {
	ProjectID   uuid.UUID `json:"projectId"`
	Environment string    `json:"environment"`
}

type ManifestImpactVersionsRow struct {
	ObjectID    uuid.UUID  `json:"objectId"`
	VersionID   uuid.UUID  `json:"versionId"`
	Body        []byte     `json:"body"`
	Path        *string    `json:"path"`
	Certified   bool       `json:"certified"`
	Stage       string     `json:"stage"`
	ChangesetID *uuid.UUID `json:"changesetId"`
}

// MF-020, MF-023: стадии сохраняются отдельно даже для одного version_id.
// Опубликованные версии выбираются только для указанного окружения; head/рабочие — по проекту.
func (q *Queries) ManifestImpactVersions(ctx context.Context, arg ManifestImpactVersionsParams) ([]ManifestImpactVersionsRow, error) {
	rows, err := q.db.Query(ctx, manifestImpactVersions, arg.ProjectID, arg.Environment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ManifestImpactVersionsRow
	for rows.Next() {
		var i ManifestImpactVersionsRow
		if err := rows.Scan(
			&i.ObjectID,
			&i.VersionID,
			&i.Body,
			&i.Path,
			&i.Certified,
			&i.Stage,
			&i.ChangesetID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pendingManifestCandidate = `-- name: PendingManifestCandidate :one
SELECT cs.id FROM changesets cs JOIN changeset_manifest_candidates b ON b.changeset_id = cs.id
WHERE b.project_id = $1 AND b.environment_id = $2 AND b.manifest_id = $3
AND b.base_manifest_id IS NOT DISTINCT FROM $4::uuid
AND cs.state NOT IN ('merged', 'abandoned') ORDER BY cs.created_at DESC LIMIT 1
`

type PendingManifestCandidateParams struct {
	ProjectID      uuid.UUID  `json:"projectId"`
	EnvironmentID  uuid.UUID  `json:"environmentId"`
	ManifestID     uuid.UUID  `json:"manifestId"`
	BaseManifestID *uuid.UUID `json:"baseManifestId"`
}

func (q *Queries) PendingManifestCandidate(ctx context.Context, arg PendingManifestCandidateParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, pendingManifestCandidate,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.ManifestID,
		arg.BaseManifestID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const recordManifestDiagnostics = `-- name: RecordManifestDiagnostics :exec
INSERT INTO changeset_manifest_diagnostics (changeset_id, project_id, environment_id, manifest_id, checked_seq, diagnostics)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (changeset_id, environment_id) DO UPDATE SET manifest_id = EXCLUDED.manifest_id,
checked_seq = EXCLUDED.checked_seq, diagnostics = EXCLUDED.diagnostics, stale = false, checked_at = now()
`

type RecordManifestDiagnosticsParams struct {
	ChangesetID   uuid.UUID  `json:"changesetId"`
	ProjectID     uuid.UUID  `json:"projectId"`
	EnvironmentID uuid.UUID  `json:"environmentId"`
	ManifestID    *uuid.UUID `json:"manifestId"`
	CheckedSeq    int32      `json:"checkedSeq"`
	Diagnostics   []byte     `json:"diagnostics"`
}

func (q *Queries) RecordManifestDiagnostics(ctx context.Context, arg RecordManifestDiagnosticsParams) error {
	_, err := q.db.Exec(ctx, recordManifestDiagnostics,
		arg.ChangesetID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.ManifestID,
		arg.CheckedSeq,
		arg.Diagnostics,
	)
	return err
}

const setActiveManifest = `-- name: SetActiveManifest :execrows
UPDATE environments SET active_manifest_id = $3
WHERE project_id = $1 AND id = $2
`

type SetActiveManifestParams struct {
	ProjectID        uuid.UUID  `json:"projectId"`
	ID               uuid.UUID  `json:"id"`
	ActiveManifestID *uuid.UUID `json:"activeManifestId"`
}

func (q *Queries) SetActiveManifest(ctx context.Context, arg SetActiveManifestParams) (int64, error) {
	result, err := q.db.Exec(ctx, setActiveManifest, arg.ProjectID, arg.ID, arg.ActiveManifestID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
