// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	"github.com/google/uuid"
)

type Actor struct {
	ID          uuid.UUID  `json:"id"`
	Kind        string     `json:"kind"`
	ProjectID   *uuid.UUID `json:"projectId"`
	DisplayName string     `json:"displayName"`
	OidcSubject *string    `json:"oidcSubject"`
	Email       *string    `json:"email"`
	DisabledAt  *time.Time `json:"disabledAt"`
	CreatedAt   time.Time  `json:"createdAt"`
}

type ApiToken struct {
	ID           uuid.UUID  `json:"id"`
	ProjectID    uuid.UUID  `json:"projectId"`
	ActorID      uuid.UUID  `json:"actorId"`
	TokenHash    []byte     `json:"tokenHash"`
	Scopes       []string   `json:"scopes"`
	Environments []string   `json:"environments"`
	ExpiresAt    time.Time  `json:"expiresAt"`
	LastUsedAt   *time.Time `json:"lastUsedAt"`
	RevokedAt    *time.Time `json:"revokedAt"`
	CreatedAt    time.Time  `json:"createdAt"`
}

type Environment struct {
	ID               uuid.UUID  `json:"id"`
	ProjectID        uuid.UUID  `json:"projectId"`
	Name             string     `json:"name"`
	Kind             string     `json:"kind"`
	ActiveManifestID *uuid.UUID `json:"activeManifestId"`
	AppUrl           *string    `json:"appUrl"`
	ExpiresAt        *time.Time `json:"expiresAt"`
	CreatedAt        time.Time  `json:"createdAt"`
}

type IdempotencyKey struct {
	ActorID     uuid.UUID `json:"actorId"`
	Key         string    `json:"key"`
	Command     string    `json:"command"`
	RequestHash []byte    `json:"requestHash"`
	Status      int32     `json:"status"`
	Response    []byte    `json:"response"`
	CreatedAt   time.Time `json:"createdAt"`
}

type Project struct {
	ID        uuid.UUID `json:"id"`
	Slug      string    `json:"slug"`
	Name      string    `json:"name"`
	Settings  []byte    `json:"settings"`
	CreatedAt time.Time `json:"createdAt"`
}

type Role struct {
	ID           uuid.UUID `json:"id"`
	ProjectID    uuid.UUID `json:"projectId"`
	Name         string    `json:"name"`
	Capabilities []string  `json:"capabilities"`
}

type RoleBinding struct {
	ProjectID uuid.UUID `json:"projectId"`
	ActorID   uuid.UUID `json:"actorId"`
	RoleID    uuid.UUID `json:"roleId"`
}
