// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	"github.com/google/uuid"
)

type Actor struct {
	ID          uuid.UUID  `json:"id"`
	Kind        string     `json:"kind"`
	ProjectID   *uuid.UUID `json:"projectId"`
	DisplayName string     `json:"displayName"`
	OidcSubject *string    `json:"oidcSubject"`
	Email       *string    `json:"email"`
	DisabledAt  *time.Time `json:"disabledAt"`
	CreatedAt   time.Time  `json:"createdAt"`
}

type ApiToken struct {
	ID           uuid.UUID  `json:"id"`
	ProjectID    uuid.UUID  `json:"projectId"`
	ActorID      uuid.UUID  `json:"actorId"`
	TokenHash    []byte     `json:"tokenHash"`
	Scopes       []string   `json:"scopes"`
	Environments []string   `json:"environments"`
	ExpiresAt    time.Time  `json:"expiresAt"`
	LastUsedAt   *time.Time `json:"lastUsedAt"`
	RevokedAt    *time.Time `json:"revokedAt"`
	CreatedAt    time.Time  `json:"createdAt"`
}

type Approval struct {
	ID            uuid.UUID  `json:"id"`
	ChangesetID   uuid.UUID  `json:"changesetId"`
	ApproverID    uuid.UUID  `json:"approverId"`
	Decision      string     `json:"decision"`
	ContentHash   []byte     `json:"contentHash"`
	Environment   string     `json:"environment"`
	Comment       *string    `json:"comment"`
	CreatedAt     time.Time  `json:"createdAt"`
	InvalidatedAt *time.Time `json:"invalidatedAt"`
}

type Changeset struct {
	ID           uuid.UUID  `json:"id"`
	ProjectID    uuid.UUID  `json:"projectId"`
	Kind         string     `json:"kind"`
	Title        string     `json:"title"`
	Description  *string    `json:"description"`
	OwnerID      uuid.UUID  `json:"ownerId"`
	State        string     `json:"state"`
	Risk         *string    `json:"risk"`
	Targets      []string   `json:"targets"`
	Seq          int32      `json:"seq"`
	ContentHash  []byte     `json:"contentHash"`
	HasConflicts bool       `json:"hasConflicts"`
	CreatedAt    time.Time  `json:"createdAt"`
	UpdatedAt    time.Time  `json:"updatedAt"`
	SubmittedAt  *time.Time `json:"submittedAt"`
	MergedAt     *time.Time `json:"mergedAt"`
}

type ChangesetObject struct {
	ChangesetID      uuid.UUID  `json:"changesetId"`
	ObjectID         uuid.UUID  `json:"objectId"`
	BaseVersionID    *uuid.UUID `json:"baseVersionId"`
	WorkingVersionID uuid.UUID  `json:"workingVersionId"`
}

type Check struct {
	ID          uuid.UUID  `json:"id"`
	ChangesetID uuid.UUID  `json:"changesetId"`
	ContentHash []byte     `json:"contentHash"`
	Environment string     `json:"environment"`
	Stage       string     `json:"stage"`
	Status      string     `json:"status"`
	Blocking    bool       `json:"blocking"`
	Details     []byte     `json:"details"`
	Artifacts   []byte     `json:"artifacts"`
	StartedAt   *time.Time `json:"startedAt"`
	FinishedAt  *time.Time `json:"finishedAt"`
}

type DeliveryKey struct {
	ID            uuid.UUID  `json:"id"`
	ProjectID     uuid.UUID  `json:"projectId"`
	EnvironmentID uuid.UUID  `json:"environmentId"`
	Name          string     `json:"name"`
	TokenHash     []byte     `json:"tokenHash"`
	CreatedBy     uuid.UUID  `json:"createdBy"`
	CreatedAt     time.Time  `json:"createdAt"`
	RevokedAt     *time.Time `json:"revokedAt"`
}

type Environment struct {
	ID               uuid.UUID  `json:"id"`
	ProjectID        uuid.UUID  `json:"projectId"`
	Name             string     `json:"name"`
	Kind             string     `json:"kind"`
	ActiveManifestID *uuid.UUID `json:"activeManifestId"`
	AppUrl           *string    `json:"appUrl"`
	ExpiresAt        *time.Time `json:"expiresAt"`
	CreatedAt        time.Time  `json:"createdAt"`
	PreviewKey       []byte     `json:"previewKey"`
}

type IdempotencyKey struct {
	ActorID     uuid.UUID `json:"actorId"`
	Key         string    `json:"key"`
	Command     string    `json:"command"`
	RequestHash []byte    `json:"requestHash"`
	Status      int32     `json:"status"`
	Response    []byte    `json:"response"`
	CreatedAt   time.Time `json:"createdAt"`
}

type Object struct {
	ID            uuid.UUID  `json:"id"`
	ProjectID     uuid.UUID  `json:"projectId"`
	Kind          string     `json:"kind"`
	SchemaName    *string    `json:"schemaName"`
	DocKind       *string    `json:"docKind"`
	HeadVersionID *uuid.UUID `json:"headVersionId"`
	HeadPath      *string    `json:"headPath"`
	CreatedAt     time.Time  `json:"createdAt"`
	DeletedAt     *time.Time `json:"deletedAt"`
}

type ObjectVersion struct {
	ID              uuid.UUID  `json:"id"`
	ProjectID       uuid.UUID  `json:"projectId"`
	ObjectID        uuid.UUID  `json:"objectId"`
	Number          *int32     `json:"number"`
	State           string     `json:"state"`
	ChangesetID     *uuid.UUID `json:"changesetId"`
	ParentVersionID *uuid.UUID `json:"parentVersionId"`
	SchemaVersion   *int32     `json:"schemaVersion"`
	IrVersion       *string    `json:"irVersion"`
	Path            *string    `json:"path"`
	Body            []byte     `json:"body"`
	BodyHash        []byte     `json:"bodyHash"`
	CreatedBy       uuid.UUID  `json:"createdBy"`
	CreatedAt       time.Time  `json:"createdAt"`
	CommittedAt     *time.Time `json:"committedAt"`
}

type Operation struct {
	ID             uuid.UUID  `json:"id"`
	ProjectID      uuid.UUID  `json:"projectId"`
	ChangesetID    uuid.UUID  `json:"changesetId"`
	Seq            int32      `json:"seq"`
	ActorID        uuid.UUID  `json:"actorId"`
	OnBehalfOf     *uuid.UUID `json:"onBehalfOf"`
	Source         string     `json:"source"`
	TargetObjectID uuid.UUID  `json:"targetObjectId"`
	Type           string     `json:"type"`
	Payload        []byte     `json:"payload"`
	Before         []byte     `json:"before"`
	After          []byte     `json:"after"`
	Inverse        []byte     `json:"inverse"`
	Reason         *string    `json:"reason"`
	ClientOpID     *string    `json:"clientOpId"`
	UndoOf         *uuid.UUID `json:"undoOf"`
	Status         string     `json:"status"`
	CreatedAt      time.Time  `json:"createdAt"`
}

type Project struct {
	ID        uuid.UUID `json:"id"`
	Slug      string    `json:"slug"`
	Name      string    `json:"name"`
	Settings  []byte    `json:"settings"`
	CreatedAt time.Time `json:"createdAt"`
}

type Publication struct {
	ID                  uuid.UUID  `json:"id"`
	ProjectID           uuid.UUID  `json:"projectId"`
	EnvironmentID       uuid.UUID  `json:"environmentId"`
	ChangesetID         *uuid.UUID `json:"changesetId"`
	Kind                string     `json:"kind"`
	SourcePublicationID *uuid.UUID `json:"sourcePublicationId"`
	ActorID             uuid.UUID  `json:"actorId"`
	Reason              *string    `json:"reason"`
	CreatedAt           time.Time  `json:"createdAt"`
}

type PublicationItem struct {
	PublicationID     uuid.UUID  `json:"publicationId"`
	ObjectID          uuid.UUID  `json:"objectId"`
	PreviousVersionID *uuid.UUID `json:"previousVersionId"`
	CurrentVersionID  *uuid.UUID `json:"currentVersionId"`
}

type PublishedPointer struct {
	EnvironmentID uuid.UUID `json:"environmentId"`
	ObjectID      uuid.UUID `json:"objectId"`
	VersionID     uuid.UUID `json:"versionId"`
	PublicationID uuid.UUID `json:"publicationId"`
}

type Role struct {
	ID           uuid.UUID `json:"id"`
	ProjectID    uuid.UUID `json:"projectId"`
	Name         string    `json:"name"`
	Capabilities []string  `json:"capabilities"`
}

type RoleBinding struct {
	ProjectID uuid.UUID `json:"projectId"`
	ActorID   uuid.UUID `json:"actorId"`
	RoleID    uuid.UUID `json:"roleId"`
}

type Route struct {
	EnvironmentID uuid.UUID `json:"environmentId"`
	Path          string    `json:"path"`
	ObjectID      uuid.UUID `json:"objectId"`
}
