// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: publishing.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addPublicationItem = `-- name: AddPublicationItem :exec
INSERT INTO publication_items (publication_id, object_id, previous_version_id, current_version_id)
VALUES ($1, $2, $3, $4)
`

type AddPublicationItemParams struct {
	PublicationID     uuid.UUID  `json:"publicationId"`
	ObjectID          uuid.UUID  `json:"objectId"`
	PreviousVersionID *uuid.UUID `json:"previousVersionId"`
	CurrentVersionID  *uuid.UUID `json:"currentVersionId"`
}

func (q *Queries) AddPublicationItem(ctx context.Context, arg AddPublicationItemParams) error {
	_, err := q.db.Exec(ctx, addPublicationItem,
		arg.PublicationID,
		arg.ObjectID,
		arg.PreviousVersionID,
		arg.CurrentVersionID,
	)
	return err
}

const commitVersion = `-- name: CommitVersion :exec
UPDATE object_versions SET state = 'committed', number = $2, committed_at = now()
WHERE id = $1 AND state = 'working'
`

type CommitVersionParams struct {
	ID     uuid.UUID `json:"id"`
	Number *int32    `json:"number"`
}

func (q *Queries) CommitVersion(ctx context.Context, arg CommitVersionParams) error {
	_, err := q.db.Exec(ctx, commitVersion, arg.ID, arg.Number)
	return err
}

const createPublication = `-- name: CreatePublication :one
INSERT INTO publications (id, project_id, environment_id, changeset_id, kind, source_publication_id, actor_id, reason)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, project_id, environment_id, changeset_id, kind, source_publication_id, actor_id, reason, created_at, previous_manifest_id, current_manifest_id, manifest_changed
`

type CreatePublicationParams struct {
	ID                  uuid.UUID  `json:"id"`
	ProjectID           uuid.UUID  `json:"projectId"`
	EnvironmentID       uuid.UUID  `json:"environmentId"`
	ChangesetID         *uuid.UUID `json:"changesetId"`
	Kind                string     `json:"kind"`
	SourcePublicationID *uuid.UUID `json:"sourcePublicationId"`
	ActorID             uuid.UUID  `json:"actorId"`
	Reason              *string    `json:"reason"`
}

func (q *Queries) CreatePublication(ctx context.Context, arg CreatePublicationParams) (Publication, error) {
	row := q.db.QueryRow(ctx, createPublication,
		arg.ID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.ChangesetID,
		arg.Kind,
		arg.SourcePublicationID,
		arg.ActorID,
		arg.Reason,
	)
	var i Publication
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.ChangesetID,
		&i.Kind,
		&i.SourcePublicationID,
		&i.ActorID,
		&i.Reason,
		&i.CreatedAt,
		&i.PreviousManifestID,
		&i.CurrentManifestID,
		&i.ManifestChanged,
	)
	return i, err
}

const deletePublishedPointer = `-- name: DeletePublishedPointer :exec
DELETE FROM published_pointers WHERE environment_id = $1 AND object_id = $2
`

type DeletePublishedPointerParams struct {
	EnvironmentID uuid.UUID `json:"environmentId"`
	ObjectID      uuid.UUID `json:"objectId"`
}

func (q *Queries) DeletePublishedPointer(ctx context.Context, arg DeletePublishedPointerParams) error {
	_, err := q.db.Exec(ctx, deletePublishedPointer, arg.EnvironmentID, arg.ObjectID)
	return err
}

const deleteRoute = `-- name: DeleteRoute :exec
DELETE FROM routes WHERE environment_id = $1 AND object_id = $2
`

type DeleteRouteParams struct {
	EnvironmentID uuid.UUID `json:"environmentId"`
	ObjectID      uuid.UUID `json:"objectId"`
}

func (q *Queries) DeleteRoute(ctx context.Context, arg DeleteRouteParams) error {
	_, err := q.db.Exec(ctx, deleteRoute, arg.EnvironmentID, arg.ObjectID)
	return err
}

const getEnvironmentByName = `-- name: GetEnvironmentByName :one
SELECT id, project_id, name, kind, active_manifest_id, app_url, expires_at, created_at, preview_key FROM environments WHERE project_id = $1 AND name = $2
`

type GetEnvironmentByNameParams struct {
	ProjectID uuid.UUID `json:"projectId"`
	Name      string    `json:"name"`
}

func (q *Queries) GetEnvironmentByName(ctx context.Context, arg GetEnvironmentByNameParams) (Environment, error) {
	row := q.db.QueryRow(ctx, getEnvironmentByName, arg.ProjectID, arg.Name)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Kind,
		&i.ActiveManifestID,
		&i.AppUrl,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.PreviewKey,
	)
	return i, err
}

const getPublication = `-- name: GetPublication :one
SELECT p.id, p.project_id, p.environment_id, p.changeset_id, p.kind, p.source_publication_id, p.actor_id, p.reason, p.created_at, p.previous_manifest_id, p.current_manifest_id, p.manifest_changed, e.name AS environment_name
FROM publications p JOIN environments e ON e.id = p.environment_id
WHERE p.id = $1 AND p.project_id = $2
`

type GetPublicationParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"projectId"`
}

type GetPublicationRow struct {
	ID                  uuid.UUID  `json:"id"`
	ProjectID           uuid.UUID  `json:"projectId"`
	EnvironmentID       uuid.UUID  `json:"environmentId"`
	ChangesetID         *uuid.UUID `json:"changesetId"`
	Kind                string     `json:"kind"`
	SourcePublicationID *uuid.UUID `json:"sourcePublicationId"`
	ActorID             uuid.UUID  `json:"actorId"`
	Reason              *string    `json:"reason"`
	CreatedAt           time.Time  `json:"createdAt"`
	PreviousManifestID  *uuid.UUID `json:"previousManifestId"`
	CurrentManifestID   *uuid.UUID `json:"currentManifestId"`
	ManifestChanged     bool       `json:"manifestChanged"`
	EnvironmentName     string     `json:"environmentName"`
}

func (q *Queries) GetPublication(ctx context.Context, arg GetPublicationParams) (GetPublicationRow, error) {
	row := q.db.QueryRow(ctx, getPublication, arg.ID, arg.ProjectID)
	var i GetPublicationRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.ChangesetID,
		&i.Kind,
		&i.SourcePublicationID,
		&i.ActorID,
		&i.Reason,
		&i.CreatedAt,
		&i.PreviousManifestID,
		&i.CurrentManifestID,
		&i.ManifestChanged,
		&i.EnvironmentName,
	)
	return i, err
}

const getPublishedDocument = `-- name: GetPublishedDocument :one
SELECT o.id, o.doc_kind, v.id AS version_id, v.state, v.path, v.body
FROM published_pointers pp
JOIN objects o ON o.id = pp.object_id
JOIN object_versions v ON v.id = pp.version_id
JOIN environments e ON e.id = pp.environment_id
WHERE pp.object_id = $1 AND o.project_id = $2 AND e.name = $3 AND o.kind = 'document'
`

type GetPublishedDocumentParams struct {
	ObjectID  uuid.UUID `json:"objectId"`
	ProjectID uuid.UUID `json:"projectId"`
	Name      string    `json:"name"`
}

type GetPublishedDocumentRow struct {
	ID        uuid.UUID `json:"id"`
	DocKind   *string   `json:"docKind"`
	VersionID uuid.UUID `json:"versionId"`
	State     string    `json:"state"`
	Path      *string   `json:"path"`
	Body      []byte    `json:"body"`
}

func (q *Queries) GetPublishedDocument(ctx context.Context, arg GetPublishedDocumentParams) (GetPublishedDocumentRow, error) {
	row := q.db.QueryRow(ctx, getPublishedDocument, arg.ObjectID, arg.ProjectID, arg.Name)
	var i GetPublishedDocumentRow
	err := row.Scan(
		&i.ID,
		&i.DocKind,
		&i.VersionID,
		&i.State,
		&i.Path,
		&i.Body,
	)
	return i, err
}

const getPublishedPointer = `-- name: GetPublishedPointer :one
SELECT environment_id, object_id, version_id, publication_id FROM published_pointers WHERE environment_id = $1 AND object_id = $2
`

type GetPublishedPointerParams struct {
	EnvironmentID uuid.UUID `json:"environmentId"`
	ObjectID      uuid.UUID `json:"objectId"`
}

func (q *Queries) GetPublishedPointer(ctx context.Context, arg GetPublishedPointerParams) (PublishedPointer, error) {
	row := q.db.QueryRow(ctx, getPublishedPointer, arg.EnvironmentID, arg.ObjectID)
	var i PublishedPointer
	err := row.Scan(
		&i.EnvironmentID,
		&i.ObjectID,
		&i.VersionID,
		&i.PublicationID,
	)
	return i, err
}

const insertRoute = `-- name: InsertRoute :exec
INSERT INTO routes (environment_id, path, object_id)
SELECT $1, v.path, v.object_id FROM object_versions v
WHERE v.id = $2 AND v.path IS NOT NULL
`

type InsertRouteParams struct {
	EnvironmentID uuid.UUID `json:"environmentId"`
	VersionID     uuid.UUID `json:"versionId"`
}

// Маршрут опубликованной версии (если у версии есть путь).
func (q *Queries) InsertRoute(ctx context.Context, arg InsertRouteParams) error {
	_, err := q.db.Exec(ctx, insertRoute, arg.EnvironmentID, arg.VersionID)
	return err
}

const listPublicationItems = `-- name: ListPublicationItems :many
SELECT publication_id, object_id, previous_version_id, current_version_id FROM publication_items WHERE publication_id = $1 ORDER BY object_id
`

func (q *Queries) ListPublicationItems(ctx context.Context, publicationID uuid.UUID) ([]PublicationItem, error) {
	rows, err := q.db.Query(ctx, listPublicationItems, publicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PublicationItem
	for rows.Next() {
		var i PublicationItem
		if err := rows.Scan(
			&i.PublicationID,
			&i.ObjectID,
			&i.PreviousVersionID,
			&i.CurrentVersionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublications = `-- name: ListPublications :many
SELECT p.id, p.project_id, p.environment_id, p.changeset_id, p.kind, p.source_publication_id, p.actor_id, p.reason, p.created_at, p.previous_manifest_id, p.current_manifest_id, p.manifest_changed, e.name AS environment_name
FROM publications p JOIN environments e ON e.id = p.environment_id
WHERE p.project_id = $1 AND ($2::text IS NULL OR e.name = $2)
ORDER BY p.created_at DESC, p.id DESC
LIMIT 100
`

type ListPublicationsParams struct {
	ProjectID   uuid.UUID `json:"projectId"`
	Environment *string   `json:"environment"`
}

type ListPublicationsRow struct {
	ID                  uuid.UUID  `json:"id"`
	ProjectID           uuid.UUID  `json:"projectId"`
	EnvironmentID       uuid.UUID  `json:"environmentId"`
	ChangesetID         *uuid.UUID `json:"changesetId"`
	Kind                string     `json:"kind"`
	SourcePublicationID *uuid.UUID `json:"sourcePublicationId"`
	ActorID             uuid.UUID  `json:"actorId"`
	Reason              *string    `json:"reason"`
	CreatedAt           time.Time  `json:"createdAt"`
	PreviousManifestID  *uuid.UUID `json:"previousManifestId"`
	CurrentManifestID   *uuid.UUID `json:"currentManifestId"`
	ManifestChanged     bool       `json:"manifestChanged"`
	EnvironmentName     string     `json:"environmentName"`
}

func (q *Queries) ListPublications(ctx context.Context, arg ListPublicationsParams) ([]ListPublicationsRow, error) {
	rows, err := q.db.Query(ctx, listPublications, arg.ProjectID, arg.Environment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublicationsRow
	for rows.Next() {
		var i ListPublicationsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.ChangesetID,
			&i.Kind,
			&i.SourcePublicationID,
			&i.ActorID,
			&i.Reason,
			&i.CreatedAt,
			&i.PreviousManifestID,
			&i.CurrentManifestID,
			&i.ManifestChanged,
			&i.EnvironmentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutes = `-- name: ListRoutes :many
SELECT r.path, r.object_id, pp.version_id
FROM routes r
JOIN environments e ON e.id = r.environment_id
JOIN published_pointers pp ON pp.environment_id = r.environment_id AND pp.object_id = r.object_id
WHERE e.project_id = $1 AND e.name = $2
ORDER BY r.path
`

type ListRoutesParams struct {
	ProjectID uuid.UUID `json:"projectId"`
	Name      string    `json:"name"`
}

type ListRoutesRow struct {
	Path      string    `json:"path"`
	ObjectID  uuid.UUID `json:"objectId"`
	VersionID uuid.UUID `json:"versionId"`
}

func (q *Queries) ListRoutes(ctx context.Context, arg ListRoutesParams) ([]ListRoutesRow, error) {
	rows, err := q.db.Query(ctx, listRoutes, arg.ProjectID, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoutesRow
	for rows.Next() {
		var i ListRoutesRow
		if err := rows.Scan(&i.Path, &i.ObjectID, &i.VersionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockObject = `-- name: LockObject :one
SELECT id, project_id, kind, schema_name, doc_kind, head_version_id, head_path, created_at, deleted_at FROM objects WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockObject(ctx context.Context, id uuid.UUID) (Object, error) {
	row := q.db.QueryRow(ctx, lockObject, id)
	var i Object
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.SchemaName,
		&i.DocKind,
		&i.HeadVersionID,
		&i.HeadPath,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const nextVersionNumber = `-- name: NextVersionNumber :one
SELECT COALESCE(max(number), 0) + 1 FROM object_versions WHERE object_id = $1
`

func (q *Queries) NextVersionNumber(ctx context.Context, objectID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextVersionNumber, objectID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const setHead = `-- name: SetHead :exec
UPDATE objects o SET head_version_id = $1::uuid,
  head_path = (SELECT v.path FROM object_versions v WHERE v.id = $1::uuid),
  deleted_at = CASE WHEN (SELECT v.deleted FROM object_versions v WHERE v.id=$1::uuid) THEN now() ELSE NULL END
WHERE o.id = $2
`

type SetHeadParams struct {
	VersionID *uuid.UUID `json:"versionId"`
	ID        uuid.UUID  `json:"id"`
}

// Head и маршрут head (из пути версии; NULL — снять).
func (q *Queries) SetHead(ctx context.Context, arg SetHeadParams) error {
	_, err := q.db.Exec(ctx, setHead, arg.VersionID, arg.ID)
	return err
}

const upsertPublishedPointer = `-- name: UpsertPublishedPointer :exec
INSERT INTO published_pointers (environment_id, object_id, version_id, publication_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (environment_id, object_id) DO UPDATE
SET version_id = EXCLUDED.version_id, publication_id = EXCLUDED.publication_id
`

type UpsertPublishedPointerParams struct {
	EnvironmentID uuid.UUID `json:"environmentId"`
	ObjectID      uuid.UUID `json:"objectId"`
	VersionID     uuid.UUID `json:"versionId"`
	PublicationID uuid.UUID `json:"publicationId"`
}

func (q *Queries) UpsertPublishedPointer(ctx context.Context, arg UpsertPublishedPointerParams) error {
	_, err := q.db.Exec(ctx, upsertPublishedPointer,
		arg.EnvironmentID,
		arg.ObjectID,
		arg.VersionID,
		arg.PublicationID,
	)
	return err
}
