// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rebase.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const deleteWorkingVersion = `-- name: DeleteWorkingVersion :exec
DELETE FROM object_versions WHERE id = $1 AND state = 'working'
`

func (q *Queries) DeleteWorkingVersion(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteWorkingVersion, id)
	return err
}

const objectOperations = `-- name: ObjectOperations :many
SELECT id, project_id, changeset_id, seq, actor_id, on_behalf_of, source, target_object_id, type, payload, before, after, inverse, reason, client_op_id, undo_of, status, created_at, target_schema_name FROM operations
WHERE changeset_id = $1 AND target_object_id = $2 AND status <> 'dropped'
ORDER BY seq
`

type ObjectOperationsParams struct {
	ChangesetID    uuid.UUID  `json:"changesetId"`
	TargetObjectID *uuid.UUID `json:"targetObjectId"`
}

// Операции Change Set над объектом в порядке seq (кроме исключённых при rebase).
func (q *Queries) ObjectOperations(ctx context.Context, arg ObjectOperationsParams) ([]Operation, error) {
	rows, err := q.db.Query(ctx, objectOperations, arg.ChangesetID, arg.TargetObjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Operation
	for rows.Next() {
		var i Operation
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ChangesetID,
			&i.Seq,
			&i.ActorID,
			&i.OnBehalfOf,
			&i.Source,
			&i.TargetObjectID,
			&i.Type,
			&i.Payload,
			&i.Before,
			&i.After,
			&i.Inverse,
			&i.Reason,
			&i.ClientOpID,
			&i.UndoOf,
			&i.Status,
			&i.CreatedAt,
			&i.TargetSchemaName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rebaseWorkingVersion = `-- name: RebaseWorkingVersion :exec
UPDATE object_versions SET parent_version_id = $2, path = $3, body = $4, body_hash = $5, certified = $6
WHERE id = $1 AND state = 'working'
`

type RebaseWorkingVersionParams struct {
	ID              uuid.UUID  `json:"id"`
	ParentVersionID *uuid.UUID `json:"parentVersionId"`
	Path            *string    `json:"path"`
	Body            []byte     `json:"body"`
	BodyHash        []byte     `json:"bodyHash"`
	Certified       bool       `json:"certified"`
}

func (q *Queries) RebaseWorkingVersion(ctx context.Context, arg RebaseWorkingVersionParams) error {
	_, err := q.db.Exec(ctx, rebaseWorkingVersion,
		arg.ID,
		arg.ParentVersionID,
		arg.Path,
		arg.Body,
		arg.BodyHash,
		arg.Certified,
	)
	return err
}

const rebindApprovals = `-- name: RebindApprovals :exec
UPDATE approvals SET content_hash = $2
WHERE changeset_id = $1 AND invalidated_at IS NULL AND content_hash = $3
`

type RebindApprovalsParams struct {
	ChangesetID uuid.UUID `json:"changesetId"`
	NewHash     []byte    `json:"newHash"`
	OldHash     []byte    `json:"oldHash"`
}

// CHG-040: согласования переходят на новое содержимое после rebase без конфликтов.
func (q *Queries) RebindApprovals(ctx context.Context, arg RebindApprovalsParams) error {
	_, err := q.db.Exec(ctx, rebindApprovals, arg.ChangesetID, arg.NewHash, arg.OldHash)
	return err
}

const removeChangesetObject = `-- name: RemoveChangesetObject :exec
DELETE FROM changeset_objects WHERE changeset_id = $1 AND object_id = $2
`

type RemoveChangesetObjectParams struct {
	ChangesetID uuid.UUID `json:"changesetId"`
	ObjectID    uuid.UUID `json:"objectId"`
}

func (q *Queries) RemoveChangesetObject(ctx context.Context, arg RemoveChangesetObjectParams) error {
	_, err := q.db.Exec(ctx, removeChangesetObject, arg.ChangesetID, arg.ObjectID)
	return err
}

const replayOperation = `-- name: ReplayOperation :exec
UPDATE operations SET status = 'applied', before = $2, after = $3, inverse = $4 WHERE id = $1
`

type ReplayOperationParams struct {
	ID      uuid.UUID `json:"id"`
	Before  []byte    `json:"before"`
	After   []byte    `json:"after"`
	Inverse []byte    `json:"inverse"`
}

// Операция переиграна на новой базе: «до», «после» и обратная операция пересчитаны.
func (q *Queries) ReplayOperation(ctx context.Context, arg ReplayOperationParams) error {
	_, err := q.db.Exec(ctx, replayOperation,
		arg.ID,
		arg.Before,
		arg.After,
		arg.Inverse,
	)
	return err
}

const setChangesetConflicts = `-- name: SetChangesetConflicts :exec
UPDATE changesets SET has_conflicts = $2, updated_at = now() WHERE id = $1
`

type SetChangesetConflictsParams struct {
	ID           uuid.UUID `json:"id"`
	HasConflicts bool      `json:"hasConflicts"`
}

func (q *Queries) SetChangesetConflicts(ctx context.Context, arg SetChangesetConflictsParams) error {
	_, err := q.db.Exec(ctx, setChangesetConflicts, arg.ID, arg.HasConflicts)
	return err
}

const setChangesetObjectBase = `-- name: SetChangesetObjectBase :exec
UPDATE changeset_objects SET base_version_id = $3 WHERE changeset_id = $1 AND object_id = $2
`

type SetChangesetObjectBaseParams struct {
	ChangesetID   uuid.UUID  `json:"changesetId"`
	ObjectID      uuid.UUID  `json:"objectId"`
	BaseVersionID *uuid.UUID `json:"baseVersionId"`
}

func (q *Queries) SetChangesetObjectBase(ctx context.Context, arg SetChangesetObjectBaseParams) error {
	_, err := q.db.Exec(ctx, setChangesetObjectBase, arg.ChangesetID, arg.ObjectID, arg.BaseVersionID)
	return err
}

const setOperationStatus = `-- name: SetOperationStatus :exec
UPDATE operations SET status = $2 WHERE id = $1
`

type SetOperationStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) SetOperationStatus(ctx context.Context, arg SetOperationStatusParams) error {
	_, err := q.db.Exec(ctx, setOperationStatus, arg.ID, arg.Status)
	return err
}
