// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schemaflow.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const claimSchemaChangeset = `-- name: ClaimSchemaChangeset :one
UPDATE changesets SET owner_id=$2, updated_at=now() WHERE id=$1 RETURNING id, project_id, kind, title, description, owner_id, state, risk, targets, seq, content_hash, has_conflicts, created_at, updated_at, submitted_at, merged_at
`

type ClaimSchemaChangesetParams struct {
	ID      uuid.UUID `json:"id"`
	OwnerID uuid.UUID `json:"ownerId"`
}

func (q *Queries) ClaimSchemaChangeset(ctx context.Context, arg ClaimSchemaChangesetParams) (Changeset, error) {
	row := q.db.QueryRow(ctx, claimSchemaChangeset, arg.ID, arg.OwnerID)
	var i Changeset
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Title,
		&i.Description,
		&i.OwnerID,
		&i.State,
		&i.Risk,
		&i.Targets,
		&i.Seq,
		&i.ContentHash,
		&i.HasConflicts,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubmittedAt,
		&i.MergedAt,
	)
	return i, err
}

const insertSchemaOperation = `-- name: InsertSchemaOperation :exec
INSERT INTO operations(id,project_id,changeset_id,seq,actor_id,source,target_schema_name,type,payload,before,after)
VALUES ($1,$2,$3,$4,$5,$6,$7,'schema.apply',$8,$9,$10)
`

type InsertSchemaOperationParams struct {
	ID               uuid.UUID `json:"id"`
	ProjectID        uuid.UUID `json:"projectId"`
	ChangesetID      uuid.UUID `json:"changesetId"`
	Seq              int32     `json:"seq"`
	ActorID          uuid.UUID `json:"actorId"`
	Source           string    `json:"source"`
	TargetSchemaName *string   `json:"targetSchemaName"`
	Payload          []byte    `json:"payload"`
	Before           []byte    `json:"before"`
	After            []byte    `json:"after"`
}

func (q *Queries) InsertSchemaOperation(ctx context.Context, arg InsertSchemaOperationParams) error {
	_, err := q.db.Exec(ctx, insertSchemaOperation,
		arg.ID,
		arg.ProjectID,
		arg.ChangesetID,
		arg.Seq,
		arg.ActorID,
		arg.Source,
		arg.TargetSchemaName,
		arg.Payload,
		arg.Before,
		arg.After,
	)
	return err
}

const publicationManifest = `-- name: PublicationManifest :exec
UPDATE publications SET previous_manifest_id=$2, current_manifest_id=$3, manifest_changed=true WHERE id=$1
`

type PublicationManifestParams struct {
	ID                 uuid.UUID  `json:"id"`
	PreviousManifestID *uuid.UUID `json:"previousManifestId"`
	CurrentManifestID  *uuid.UUID `json:"currentManifestId"`
}

func (q *Queries) PublicationManifest(ctx context.Context, arg PublicationManifestParams) error {
	_, err := q.db.Exec(ctx, publicationManifest, arg.ID, arg.PreviousManifestID, arg.CurrentManifestID)
	return err
}

const recordSchemaClaim = `-- name: RecordSchemaClaim :exec
INSERT INTO schema_changeset_claims(id,changeset_id,previous_owner_id,owner_id) VALUES($1,$2,$3,$4)
`

type RecordSchemaClaimParams struct {
	ID              uuid.UUID `json:"id"`
	ChangesetID     uuid.UUID `json:"changesetId"`
	PreviousOwnerID uuid.UUID `json:"previousOwnerId"`
	OwnerID         uuid.UUID `json:"ownerId"`
}

func (q *Queries) RecordSchemaClaim(ctx context.Context, arg RecordSchemaClaimParams) error {
	_, err := q.db.Exec(ctx, recordSchemaClaim,
		arg.ID,
		arg.ChangesetID,
		arg.PreviousOwnerID,
		arg.OwnerID,
	)
	return err
}

const schemaOperations = `-- name: SchemaOperations :many
SELECT id, project_id, changeset_id, seq, actor_id, on_behalf_of, source, target_object_id, type, payload, before, after, inverse, reason, client_op_id, undo_of, status, created_at, target_schema_name FROM operations WHERE changeset_id=$1 AND type='schema.apply' AND status='applied' ORDER BY seq
`

func (q *Queries) SchemaOperations(ctx context.Context, changesetID uuid.UUID) ([]Operation, error) {
	rows, err := q.db.Query(ctx, schemaOperations, changesetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Operation
	for rows.Next() {
		var i Operation
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ChangesetID,
			&i.Seq,
			&i.ActorID,
			&i.OnBehalfOf,
			&i.Source,
			&i.TargetObjectID,
			&i.Type,
			&i.Payload,
			&i.Before,
			&i.After,
			&i.Inverse,
			&i.Reason,
			&i.ClientOpID,
			&i.UndoOf,
			&i.Status,
			&i.CreatedAt,
			&i.TargetSchemaName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const schemaOwner = `-- name: SchemaOwner :one
SELECT a.kind FROM changesets cs JOIN actors a ON a.id=cs.owner_id WHERE cs.id=$1
`

func (q *Queries) SchemaOwner(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, schemaOwner, id)
	var kind string
	err := row.Scan(&kind)
	return kind, err
}
