// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: validation.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const validationCandidate = `-- name: ValidationCandidate :one
SELECT b.changeset_id, b.project_id, b.environment_id, b.manifest_id, b.base_manifest_id, m.hash, m.body, cs.kind FROM changeset_manifest_candidates b
JOIN manifests m ON m.id = b.manifest_id AND m.project_id = b.project_id
JOIN changesets cs ON cs.id = b.changeset_id AND cs.project_id = b.project_id
WHERE b.project_id = $1 AND b.changeset_id = $2
`

type ValidationCandidateParams struct {
	ProjectID   uuid.UUID `json:"projectId"`
	ChangesetID uuid.UUID `json:"changesetId"`
}

type ValidationCandidateRow struct {
	ChangesetID    uuid.UUID  `json:"changesetId"`
	ProjectID      uuid.UUID  `json:"projectId"`
	EnvironmentID  uuid.UUID  `json:"environmentId"`
	ManifestID     uuid.UUID  `json:"manifestId"`
	BaseManifestID *uuid.UUID `json:"baseManifestId"`
	Hash           string     `json:"hash"`
	Body           []byte     `json:"body"`
	Kind           string     `json:"kind"`
}

func (q *Queries) ValidationCandidate(ctx context.Context, arg ValidationCandidateParams) (ValidationCandidateRow, error) {
	row := q.db.QueryRow(ctx, validationCandidate, arg.ProjectID, arg.ChangesetID)
	var i ValidationCandidateRow
	err := row.Scan(
		&i.ChangesetID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.ManifestID,
		&i.BaseManifestID,
		&i.Hash,
		&i.Body,
		&i.Kind,
	)
	return i, err
}

const validationComponent = `-- name: ValidationComponent :one
SELECT v.id, v.body, v.path, v.certified FROM objects o
JOIN object_versions v ON v.object_id = o.id AND v.project_id = o.project_id
WHERE o.project_id = $1 AND o.id = $2
AND o.kind = 'document' AND o.doc_kind = 'component' AND o.deleted_at IS NULL
AND (($3::int > 0 AND v.state = 'committed' AND v.number = $3)
 OR ($3::int = 0 AND v.id = COALESCE(
   (SELECT co.working_version_id FROM changeset_objects co JOIN changesets cs ON cs.id = co.changeset_id
    WHERE co.object_id = o.id AND co.changeset_id = $4::uuid AND cs.project_id = o.project_id
      AND cs.state NOT IN ('merged', 'abandoned')),
   CASE WHEN $5::boolean THEN o.head_version_id ELSE
   (SELECT pp.version_id FROM published_pointers pp JOIN environments e ON e.id = pp.environment_id
    WHERE pp.object_id = o.id AND e.id = $6 AND e.project_id = o.project_id) END)))
`

type ValidationComponentParams struct {
	ProjectID     uuid.UUID  `json:"projectId"`
	ObjectID      uuid.UUID  `json:"objectId"`
	Number        int32      `json:"number"`
	ChangesetID   *uuid.UUID `json:"changesetId"`
	UseHead       bool       `json:"useHead"`
	EnvironmentID uuid.UUID  `json:"environmentId"`
}

type ValidationComponentRow struct {
	ID        uuid.UUID `json:"id"`
	Body      []byte    `json:"body"`
	Path      *string   `json:"path"`
	Certified bool      `json:"certified"`
}

func (q *Queries) ValidationComponent(ctx context.Context, arg ValidationComponentParams) (ValidationComponentRow, error) {
	row := q.db.QueryRow(ctx, validationComponent,
		arg.ProjectID,
		arg.ObjectID,
		arg.Number,
		arg.ChangesetID,
		arg.UseHead,
		arg.EnvironmentID,
	)
	var i ValidationComponentRow
	err := row.Scan(
		&i.ID,
		&i.Body,
		&i.Path,
		&i.Certified,
	)
	return i, err
}

const validationPage = `-- name: ValidationPage :one
SELECT v.path FROM objects o
JOIN object_versions v ON v.object_id = o.id AND v.project_id = o.project_id
WHERE o.project_id = $1 AND o.id = $2
AND o.kind = 'document' AND o.doc_kind = 'page' AND o.deleted_at IS NULL
AND v.id = COALESCE(
 (SELECT co.working_version_id FROM changeset_objects co JOIN changesets cs ON cs.id = co.changeset_id
  WHERE co.object_id = o.id AND co.changeset_id = $3::uuid AND cs.project_id = o.project_id
    AND cs.state NOT IN ('merged', 'abandoned')),
 CASE WHEN $4::boolean THEN o.head_version_id ELSE
 (SELECT pp.version_id FROM published_pointers pp JOIN environments e ON e.id = pp.environment_id
  WHERE pp.object_id = o.id AND e.id = $5 AND e.project_id = o.project_id) END)
`

type ValidationPageParams struct {
	ProjectID     uuid.UUID  `json:"projectId"`
	ObjectID      uuid.UUID  `json:"objectId"`
	ChangesetID   *uuid.UUID `json:"changesetId"`
	UseHead       bool       `json:"useHead"`
	EnvironmentID uuid.UUID  `json:"environmentId"`
}

func (q *Queries) ValidationPage(ctx context.Context, arg ValidationPageParams) (*string, error) {
	row := q.db.QueryRow(ctx, validationPage,
		arg.ProjectID,
		arg.ObjectID,
		arg.ChangesetID,
		arg.UseHead,
		arg.EnvironmentID,
	)
	var path *string
	err := row.Scan(&path)
	return path, err
}

const validationPublishedVersions = `-- name: ValidationPublishedVersions :many
SELECT o.id AS object_id, v.id AS version_id, v.body, v.path, v.certified
FROM published_pointers pp JOIN environments e ON e.id = pp.environment_id
JOIN objects o ON o.id = pp.object_id
JOIN object_versions v ON v.id = pp.version_id AND v.object_id = o.id
WHERE e.project_id = $1 AND e.id = $2 AND o.project_id = e.project_id
ORDER BY o.id
`

type ValidationPublishedVersionsParams struct {
	ProjectID uuid.UUID `json:"projectId"`
	ID        uuid.UUID `json:"id"`
}

type ValidationPublishedVersionsRow struct {
	ObjectID  uuid.UUID `json:"objectId"`
	VersionID uuid.UUID `json:"versionId"`
	Body      []byte    `json:"body"`
	Path      *string   `json:"path"`
	Certified bool      `json:"certified"`
}

func (q *Queries) ValidationPublishedVersions(ctx context.Context, arg ValidationPublishedVersionsParams) ([]ValidationPublishedVersionsRow, error) {
	rows, err := q.db.Query(ctx, validationPublishedVersions, arg.ProjectID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ValidationPublishedVersionsRow
	for rows.Next() {
		var i ValidationPublishedVersionsRow
		if err := rows.Scan(
			&i.ObjectID,
			&i.VersionID,
			&i.Body,
			&i.Path,
			&i.Certified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
