// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workflow.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const changesetAuthors = `-- name: ChangesetAuthors :many
SELECT a.actor_id AS author_id FROM operations a WHERE a.changeset_id = $1::uuid
UNION
SELECT b.on_behalf_of FROM operations b WHERE b.changeset_id = $1::uuid AND b.on_behalf_of IS NOT NULL
`

// UNION убирает повторы; «DISTINCT on_behalf_of» парсер принял бы за DISTINCT ON.
func (q *Queries) ChangesetAuthors(ctx context.Context, changesetID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, changesetAuthors, changesetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var author_id uuid.UUID
		if err := rows.Scan(&author_id); err != nil {
			return nil, err
		}
		items = append(items, author_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const changesetBaseMismatches = `-- name: ChangesetBaseMismatches :many
SELECT co.object_id
FROM changeset_objects co
JOIN objects o ON o.id = co.object_id
WHERE co.changeset_id = $1
  AND o.head_version_id IS DISTINCT FROM co.base_version_id
ORDER BY co.object_id
`

// Объекты Change Set, head которых изменился после начала работы (нужен rebase).
func (q *Queries) ChangesetBaseMismatches(ctx context.Context, changesetID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, changesetBaseMismatches, changesetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var object_id uuid.UUID
		if err := rows.Scan(&object_id); err != nil {
			return nil, err
		}
		items = append(items, object_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const changesetOperationActors = `-- name: ChangesetOperationActors :many
SELECT DISTINCT actor_id, type FROM operations WHERE changeset_id = $1 AND status = 'applied'
`

type ChangesetOperationActorsRow struct {
	ActorID uuid.UUID `json:"actorId"`
	Type    string    `json:"type"`
}

func (q *Queries) ChangesetOperationActors(ctx context.Context, changesetID uuid.UUID) ([]ChangesetOperationActorsRow, error) {
	rows, err := q.db.Query(ctx, changesetOperationActors, changesetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChangesetOperationActorsRow
	for rows.Next() {
		var i ChangesetOperationActorsRow
		if err := rows.Scan(&i.ActorID, &i.Type); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const changesetWorkingVersions = `-- name: ChangesetWorkingVersions :many
SELECT co.object_id, co.base_version_id, v.id AS version_id, v.body, v.body_hash
FROM changeset_objects co
JOIN object_versions v ON v.id = co.working_version_id
WHERE co.changeset_id = $1
ORDER BY co.object_id
`

type ChangesetWorkingVersionsRow struct {
	ObjectID      uuid.UUID  `json:"objectId"`
	BaseVersionID *uuid.UUID `json:"baseVersionId"`
	VersionID     uuid.UUID  `json:"versionId"`
	Body          []byte     `json:"body"`
	BodyHash      []byte     `json:"bodyHash"`
}

func (q *Queries) ChangesetWorkingVersions(ctx context.Context, changesetID uuid.UUID) ([]ChangesetWorkingVersionsRow, error) {
	rows, err := q.db.Query(ctx, changesetWorkingVersions, changesetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChangesetWorkingVersionsRow
	for rows.Next() {
		var i ChangesetWorkingVersionsRow
		if err := rows.Scan(
			&i.ObjectID,
			&i.BaseVersionID,
			&i.VersionID,
			&i.Body,
			&i.BodyHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countValidApprovals = `-- name: CountValidApprovals :one
SELECT count(DISTINCT approver_id) FROM approvals
WHERE changeset_id = $1 AND content_hash = $2 AND decision = 'approve' AND invalidated_at IS NULL
`

type CountValidApprovalsParams struct {
	ChangesetID uuid.UUID `json:"changesetId"`
	ContentHash []byte    `json:"contentHash"`
}

func (q *Queries) CountValidApprovals(ctx context.Context, arg CountValidApprovalsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countValidApprovals, arg.ChangesetID, arg.ContentHash)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getProjectSettings = `-- name: GetProjectSettings :one
SELECT settings FROM projects WHERE id = $1
`

func (q *Queries) GetProjectSettings(ctx context.Context, id uuid.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getProjectSettings, id)
	var settings []byte
	err := row.Scan(&settings)
	return settings, err
}

const insertApproval = `-- name: InsertApproval :exec
INSERT INTO approvals (id, changeset_id, approver_id, decision, content_hash, comment)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertApprovalParams struct {
	ID          uuid.UUID `json:"id"`
	ChangesetID uuid.UUID `json:"changesetId"`
	ApproverID  uuid.UUID `json:"approverId"`
	Decision    string    `json:"decision"`
	ContentHash []byte    `json:"contentHash"`
	Comment     *string   `json:"comment"`
}

func (q *Queries) InsertApproval(ctx context.Context, arg InsertApprovalParams) error {
	_, err := q.db.Exec(ctx, insertApproval,
		arg.ID,
		arg.ChangesetID,
		arg.ApproverID,
		arg.Decision,
		arg.ContentHash,
		arg.Comment,
	)
	return err
}

const insertCheck = `-- name: InsertCheck :exec
INSERT INTO checks (id, changeset_id, content_hash, stage, status, blocking, details, started_at, finished_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, now(), now())
`

type InsertCheckParams struct {
	ID          uuid.UUID `json:"id"`
	ChangesetID uuid.UUID `json:"changesetId"`
	ContentHash []byte    `json:"contentHash"`
	Stage       string    `json:"stage"`
	Status      string    `json:"status"`
	Blocking    bool      `json:"blocking"`
	Details     []byte    `json:"details"`
}

func (q *Queries) InsertCheck(ctx context.Context, arg InsertCheckParams) error {
	_, err := q.db.Exec(ctx, insertCheck,
		arg.ID,
		arg.ChangesetID,
		arg.ContentHash,
		arg.Stage,
		arg.Status,
		arg.Blocking,
		arg.Details,
	)
	return err
}

const invalidateApprovals = `-- name: InvalidateApprovals :exec
UPDATE approvals SET invalidated_at = now() WHERE changeset_id = $1 AND invalidated_at IS NULL
`

func (q *Queries) InvalidateApprovals(ctx context.Context, changesetID uuid.UUID) error {
	_, err := q.db.Exec(ctx, invalidateApprovals, changesetID)
	return err
}

const listApprovals = `-- name: ListApprovals :many
SELECT id, changeset_id, approver_id, decision, content_hash, environment, comment, created_at, invalidated_at FROM approvals WHERE changeset_id = $1 ORDER BY created_at
`

func (q *Queries) ListApprovals(ctx context.Context, changesetID uuid.UUID) ([]Approval, error) {
	rows, err := q.db.Query(ctx, listApprovals, changesetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Approval
	for rows.Next() {
		var i Approval
		if err := rows.Scan(
			&i.ID,
			&i.ChangesetID,
			&i.ApproverID,
			&i.Decision,
			&i.ContentHash,
			&i.Environment,
			&i.Comment,
			&i.CreatedAt,
			&i.InvalidatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChecks = `-- name: ListChecks :many
SELECT id, changeset_id, content_hash, environment, stage, status, blocking, details, artifacts, started_at, finished_at FROM checks WHERE changeset_id = $1 AND content_hash = $2 ORDER BY stage
`

type ListChecksParams struct {
	ChangesetID uuid.UUID `json:"changesetId"`
	ContentHash []byte    `json:"contentHash"`
}

func (q *Queries) ListChecks(ctx context.Context, arg ListChecksParams) ([]Check, error) {
	rows, err := q.db.Query(ctx, listChecks, arg.ChangesetID, arg.ContentHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Check
	for rows.Next() {
		var i Check
		if err := rows.Scan(
			&i.ID,
			&i.ChangesetID,
			&i.ContentHash,
			&i.Environment,
			&i.Stage,
			&i.Status,
			&i.Blocking,
			&i.Details,
			&i.Artifacts,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mergeChangeset = `-- name: MergeChangeset :exec
UPDATE changesets SET state = 'merged', merged_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) MergeChangeset(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, mergeChangeset, id)
	return err
}

const setProjectSettings = `-- name: SetProjectSettings :exec
UPDATE projects SET settings = $2 WHERE id = $1
`

type SetProjectSettingsParams struct {
	ID       uuid.UUID `json:"id"`
	Settings []byte    `json:"settings"`
}

func (q *Queries) SetProjectSettings(ctx context.Context, arg SetProjectSettingsParams) error {
	_, err := q.db.Exec(ctx, setProjectSettings, arg.ID, arg.Settings)
	return err
}

const submitChangeset = `-- name: SubmitChangeset :exec
UPDATE changesets SET state = $2, risk = $3, content_hash = $4, targets = $5,
  submitted_at = now(), updated_at = now()
WHERE id = $1
`

type SubmitChangesetParams struct {
	ID          uuid.UUID `json:"id"`
	State       string    `json:"state"`
	Risk        *string   `json:"risk"`
	ContentHash []byte    `json:"contentHash"`
	Targets     []string  `json:"targets"`
}

func (q *Queries) SubmitChangeset(ctx context.Context, arg SubmitChangesetParams) error {
	_, err := q.db.Exec(ctx, submitChangeset,
		arg.ID,
		arg.State,
		arg.Risk,
		arg.ContentHash,
		arg.Targets,
	)
	return err
}
