// Code generated by cmd/irgen from packages/ir/schema/ir-1.0.schema.json. DO NOT EDIT.

package ir

type ActionArg interface{}

type ActionCall struct {
	// Action corresponds to the JSON schema field "action".
	Action string `json:"action" yaml:"action" mapstructure:"action"`

	// Args corresponds to the JSON schema field "args".
	Args ActionCallArgs `json:"args,omitempty,omitzero" yaml:"args,omitempty" mapstructure:"args,omitempty"`
}

type ActionCallArgs map[string]ActionArg

type Binding interface{}

type ContentDeclaration struct {
	// Resolve corresponds to the JSON schema field "resolve".
	Resolve interface{} `json:"resolve" yaml:"resolve" mapstructure:"resolve"`

	// Schema corresponds to the JSON schema field "schema".
	Schema string `json:"schema" yaml:"schema" mapstructure:"schema"`
}

type DataSourceUse struct {
	// Params corresponds to the JSON schema field "params".
	Params DataSourceUseParams `json:"params,omitempty,omitzero" yaml:"params,omitempty" mapstructure:"params,omitempty"`

	// Source corresponds to the JSON schema field "source".
	Source string `json:"source" yaml:"source" mapstructure:"source"`
}

type DataSourceUseParams map[string]Operand

// Design — дизайн-свойства узла: имя свойства → DesignValue; ключ "states" → DesignStates.
type Design map[string]any

type DesignStates map[string]map[string]ScalarDesignValue

type DesignValue interface{}

type Format struct {
	// Args corresponds to the JSON schema field "args".
	Args FormatArgs `json:"args,omitempty,omitzero" yaml:"args,omitempty" mapstructure:"args,omitempty"`

	// Fn corresponds to the JSON schema field "fn".
	Fn string `json:"fn" yaml:"fn" mapstructure:"fn"`
}

type FormatArgs map[string]interface{}

type Identifier string

// Структурная схема (уровень валидации L1). Проверки по manifest, привязкам,
// дизайну и политикам выполняются отдельными валидаторами (см. 02-ir.md §11).
type Document struct {
	// Content corresponds to the JSON schema field "content".
	Content *ContentDeclaration `json:"content,omitempty,omitzero" yaml:"content,omitempty" mapstructure:"content,omitempty"`

	// DataSources corresponds to the JSON schema field "dataSources".
	DataSources DocumentDataSources `json:"dataSources,omitempty,omitzero" yaml:"dataSources,omitempty" mapstructure:"dataSources,omitempty"`

	// Inputs corresponds to the JSON schema field "inputs".
	Inputs DocumentInputs `json:"inputs,omitempty,omitzero" yaml:"inputs,omitempty" mapstructure:"inputs,omitempty"`

	// IrVersion corresponds to the JSON schema field "irVersion".
	IrVersion interface{} `json:"irVersion" yaml:"irVersion" mapstructure:"irVersion"`

	// Kind corresponds to the JSON schema field "kind".
	Kind DocumentKind `json:"kind" yaml:"kind" mapstructure:"kind"`

	// LocalContent corresponds to the JSON schema field "localContent".
	LocalContent DocumentLocalContent `json:"localContent,omitempty,omitzero" yaml:"localContent,omitempty" mapstructure:"localContent,omitempty"`

	// Meta corresponds to the JSON schema field "meta".
	Meta *DocumentMeta `json:"meta,omitempty,omitzero" yaml:"meta,omitempty" mapstructure:"meta,omitempty"`

	// Nodes corresponds to the JSON schema field "nodes".
	Nodes DocumentNodes `json:"nodes" yaml:"nodes" mapstructure:"nodes"`

	// Policy corresponds to the JSON schema field "policy".
	Policy *Policy `json:"policy,omitempty,omitzero" yaml:"policy,omitempty" mapstructure:"policy,omitempty"`

	// Root corresponds to the JSON schema field "root".
	Root NodeId `json:"root" yaml:"root" mapstructure:"root"`

	// SlotDefs corresponds to the JSON schema field "slotDefs".
	SlotDefs DocumentSlotDefs `json:"slotDefs,omitempty,omitzero" yaml:"slotDefs,omitempty" mapstructure:"slotDefs,omitempty"`
}

type DocumentDataSources map[string]DataSourceUse

type DocumentInputs map[string]TypeDef

type DocumentKind string

const DocumentKindComponent DocumentKind = "component"
const DocumentKindPage DocumentKind = "page"

type DocumentLocalContent map[string]LocalContentItem

type DocumentMeta struct {
	// Description corresponds to the JSON schema field "description".
	Description *string `json:"description,omitempty,omitzero" yaml:"description,omitempty" mapstructure:"description,omitempty"`

	// ThumbnailAssetId corresponds to the JSON schema field "thumbnailAssetId".
	ThumbnailAssetId *Uuid `json:"thumbnailAssetId,omitempty,omitzero" yaml:"thumbnailAssetId,omitempty" mapstructure:"thumbnailAssetId,omitempty"`

	// Title corresponds to the JSON schema field "title".
	Title *string `json:"title,omitempty,omitzero" yaml:"title,omitempty" mapstructure:"title,omitempty"`
}

type DocumentNodes map[string]Node

type DocumentSlotDefs map[string]SlotDef

type Link map[string]interface{}

type Literal struct {
	// Lit corresponds to the JSON schema field "lit".
	Lit interface{} `json:"lit" yaml:"lit" mapstructure:"lit"`
}

type LocalContentItem struct {
	// Type corresponds to the JSON schema field "type".
	Type LocalContentItemType `json:"type" yaml:"type" mapstructure:"type"`

	// Value corresponds to the JSON schema field "value".
	Value LocalContentItemValue `json:"value" yaml:"value" mapstructure:"value"`
}

type LocalContentItemType string

const LocalContentItemTypeAsset LocalContentItemType = "asset"
const LocalContentItemTypeLink LocalContentItemType = "link"
const LocalContentItemTypeRichText LocalContentItemType = "richText"
const LocalContentItemTypeText LocalContentItemType = "text"

type LocalContentItemValue map[string]interface{}

type Mode string

const ModeCODE Mode = "CODE"
const ModeFREE Mode = "FREE"
const ModeSTRICT Mode = "STRICT"
const ModeSYSTEM Mode = "SYSTEM"

type Node struct {
	// Bindings corresponds to the JSON schema field "bindings".
	Bindings NodeBindings `json:"bindings,omitempty,omitzero" yaml:"bindings,omitempty" mapstructure:"bindings,omitempty"`

	// Children corresponds to the JSON schema field "children".
	Children []NodeId `json:"children,omitempty,omitzero" yaml:"children,omitempty" mapstructure:"children,omitempty"`

	// Design corresponds to the JSON schema field "design".
	Design *Design `json:"design,omitempty,omitzero" yaml:"design,omitempty" mapstructure:"design,omitempty"`

	// Id corresponds to the JSON schema field "id".
	Id NodeId `json:"id" yaml:"id" mapstructure:"id"`

	// Locked corresponds to the JSON schema field "locked".
	Locked *bool `json:"locked,omitempty,omitzero" yaml:"locked,omitempty" mapstructure:"locked,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name *string `json:"name,omitempty,omitzero" yaml:"name,omitempty" mapstructure:"name,omitempty"`

	// On corresponds to the JSON schema field "on".
	On NodeOn `json:"on,omitempty,omitzero" yaml:"on,omitempty" mapstructure:"on,omitempty"`

	// Props corresponds to the JSON schema field "props".
	Props NodeProps `json:"props,omitempty,omitzero" yaml:"props,omitempty" mapstructure:"props,omitempty"`

	// Ref corresponds to the JSON schema field "ref".
	Ref *NodeRef `json:"ref,omitempty,omitzero" yaml:"ref,omitempty" mapstructure:"ref,omitempty"`

	// Slots corresponds to the JSON schema field "slots".
	Slots NodeSlots `json:"slots,omitempty,omitzero" yaml:"slots,omitempty" mapstructure:"slots,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type" yaml:"type" mapstructure:"type"`

	// When corresponds to the JSON schema field "when".
	When Predicate `json:"when,omitempty,omitzero" yaml:"when,omitempty" mapstructure:"when,omitempty"`

	// Zone corresponds to the JSON schema field "zone".
	Zone interface{} `json:"zone,omitempty,omitzero" yaml:"zone,omitempty" mapstructure:"zone,omitempty"`
}

type NodeBindings map[string]Binding

type NodeId string

type NodeOn map[string]interface{}

type NodeProps map[string]interface{}

type NodeRef struct {
	// Component corresponds to the JSON schema field "component".
	Component Uuid `json:"component" yaml:"component" mapstructure:"component"`

	// Version corresponds to the JSON schema field "version".
	Version interface{} `json:"version,omitempty,omitzero" yaml:"version,omitempty" mapstructure:"version,omitempty"`
}

type NodeSlots map[string][]NodeId

type Operand interface{}

type Path string

type Policy struct {
	// AllowRawColors corresponds to the JSON schema field "allowRawColors".
	AllowRawColors *bool `json:"allowRawColors,omitempty,omitzero" yaml:"allowRawColors,omitempty" mapstructure:"allowRawColors,omitempty"`

	// AllowedTypes corresponds to the JSON schema field "allowedTypes".
	AllowedTypes []string `json:"allowedTypes,omitempty,omitzero" yaml:"allowedTypes,omitempty" mapstructure:"allowedTypes,omitempty"`

	// DeniedTypes corresponds to the JSON schema field "deniedTypes".
	DeniedTypes []string `json:"deniedTypes,omitempty,omitzero" yaml:"deniedTypes,omitempty" mapstructure:"deniedTypes,omitempty"`

	// MaxMode corresponds to the JSON schema field "maxMode".
	MaxMode *Mode `json:"maxMode,omitempty,omitzero" yaml:"maxMode,omitempty" mapstructure:"maxMode,omitempty"`

	// Mode corresponds to the JSON schema field "mode".
	Mode *Mode `json:"mode,omitempty,omitzero" yaml:"mode,omitempty" mapstructure:"mode,omitempty"`
}

type Predicate map[string]interface{}

type RawValue struct {
	// Raw corresponds to the JSON schema field "raw".
	Raw interface{} `json:"raw" yaml:"raw" mapstructure:"raw"`
}

// ResponsiveValue — значение по breakpoint'ам; ключ "base" обязателен.
type ResponsiveValue map[string]ScalarDesignValue

type ScalarDesignValue interface{}

type SlotDef struct {
	// AllowedTypes corresponds to the JSON schema field "allowedTypes".
	AllowedTypes []string `json:"allowedTypes,omitempty,omitzero" yaml:"allowedTypes,omitempty" mapstructure:"allowedTypes,omitempty"`

	// Max corresponds to the JSON schema field "max".
	Max *int `json:"max,omitempty,omitzero" yaml:"max,omitempty" mapstructure:"max,omitempty"`

	// Min corresponds to the JSON schema field "min".
	Min *int `json:"min,omitempty,omitzero" yaml:"min,omitempty" mapstructure:"min,omitempty"`
}

type TypeDef struct {
	// AssetKind corresponds to the JSON schema field "assetKind".
	AssetKind *TypeDefAssetKind `json:"assetKind,omitempty,omitzero" yaml:"assetKind,omitempty" mapstructure:"assetKind,omitempty"`

	// Content corresponds to the JSON schema field "content".
	Content *bool `json:"content,omitempty,omitzero" yaml:"content,omitempty" mapstructure:"content,omitempty"`

	// Default corresponds to the JSON schema field "default".
	Default interface{} `json:"default,omitempty,omitzero" yaml:"default,omitempty" mapstructure:"default,omitempty"`

	// Description corresponds to the JSON schema field "description".
	Description *string `json:"description,omitempty,omitzero" yaml:"description,omitempty" mapstructure:"description,omitempty"`

	// Fields corresponds to the JSON schema field "fields".
	Fields TypeDefFields `json:"fields,omitempty,omitzero" yaml:"fields,omitempty" mapstructure:"fields,omitempty"`

	// Integer corresponds to the JSON schema field "integer".
	Integer *bool `json:"integer,omitempty,omitzero" yaml:"integer,omitempty" mapstructure:"integer,omitempty"`

	// Localized corresponds to the JSON schema field "localized".
	Localized *bool `json:"localized,omitempty,omitzero" yaml:"localized,omitempty" mapstructure:"localized,omitempty"`

	// Max corresponds to the JSON schema field "max".
	Max *float64 `json:"max,omitempty,omitzero" yaml:"max,omitempty" mapstructure:"max,omitempty"`

	// MaxLength corresponds to the JSON schema field "maxLength".
	MaxLength *int `json:"maxLength,omitempty,omitzero" yaml:"maxLength,omitempty" mapstructure:"maxLength,omitempty"`

	// Min corresponds to the JSON schema field "min".
	Min *float64 `json:"min,omitempty,omitzero" yaml:"min,omitempty" mapstructure:"min,omitempty"`

	// MinLength corresponds to the JSON schema field "minLength".
	MinLength *int `json:"minLength,omitempty,omitzero" yaml:"minLength,omitempty" mapstructure:"minLength,omitempty"`

	// Multiline corresponds to the JSON schema field "multiline".
	Multiline *bool `json:"multiline,omitempty,omitzero" yaml:"multiline,omitempty" mapstructure:"multiline,omitempty"`

	// Of corresponds to the JSON schema field "of".
	Of *TypeDef `json:"of,omitempty,omitzero" yaml:"of,omitempty" mapstructure:"of,omitempty"`

	// Pattern corresponds to the JSON schema field "pattern".
	Pattern *string `json:"pattern,omitempty,omitzero" yaml:"pattern,omitempty" mapstructure:"pattern,omitempty"`

	// Required corresponds to the JSON schema field "required".
	Required *bool `json:"required,omitempty,omitzero" yaml:"required,omitempty" mapstructure:"required,omitempty"`

	// Responsive corresponds to the JSON schema field "responsive".
	Responsive *bool `json:"responsive,omitempty,omitzero" yaml:"responsive,omitempty" mapstructure:"responsive,omitempty"`

	// Schema corresponds to the JSON schema field "schema".
	Schema *string `json:"schema,omitempty,omitzero" yaml:"schema,omitempty" mapstructure:"schema,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type TypeDefType `json:"type" yaml:"type" mapstructure:"type"`

	// Values corresponds to the JSON schema field "values".
	Values []string `json:"values,omitempty,omitzero" yaml:"values,omitempty" mapstructure:"values,omitempty"`
}

type TypeDefAssetKind string

const TypeDefAssetKindFile TypeDefAssetKind = "file"
const TypeDefAssetKindImage TypeDefAssetKind = "image"
const TypeDefAssetKindVideo TypeDefAssetKind = "video"

type TypeDefFields map[string]TypeDef

type TypeDefType string

const TypeDefTypeAsset TypeDefType = "asset"
const TypeDefTypeBoolean TypeDefType = "boolean"
const TypeDefTypeColor TypeDefType = "color"
const TypeDefTypeDate TypeDefType = "date"
const TypeDefTypeDatetime TypeDefType = "datetime"
const TypeDefTypeEnum TypeDefType = "enum"
const TypeDefTypeLink TypeDefType = "link"
const TypeDefTypeList TypeDefType = "list"
const TypeDefTypeNodeRef TypeDefType = "nodeRef"
const TypeDefTypeNumber TypeDefType = "number"
const TypeDefTypeObject TypeDefType = "object"
const TypeDefTypeReference TypeDefType = "reference"
const TypeDefTypeRichText TypeDefType = "richText"
const TypeDefTypeString TypeDefType = "string"
const TypeDefTypeText TypeDefType = "text"
const TypeDefTypeUrl TypeDefType = "url"

type Uuid string

type Zone struct {
	// AllowedTypes corresponds to the JSON schema field "allowedTypes".
	AllowedTypes []string `json:"allowedTypes,omitempty,omitzero" yaml:"allowedTypes,omitempty" mapstructure:"allowedTypes,omitempty"`

	// DeniedTypes corresponds to the JSON schema field "deniedTypes".
	DeniedTypes []string `json:"deniedTypes,omitempty,omitzero" yaml:"deniedTypes,omitempty" mapstructure:"deniedTypes,omitempty"`

	// Id corresponds to the JSON schema field "id".
	Id Identifier `json:"id" yaml:"id" mapstructure:"id"`

	// Locked corresponds to the JSON schema field "locked".
	Locked *bool `json:"locked,omitempty,omitzero" yaml:"locked,omitempty" mapstructure:"locked,omitempty"`

	// MaxMode corresponds to the JSON schema field "maxMode".
	MaxMode *Mode `json:"maxMode,omitempty,omitzero" yaml:"maxMode,omitempty" mapstructure:"maxMode,omitempty"`

	// Mode corresponds to the JSON schema field "mode".
	Mode Mode `json:"mode" yaml:"mode" mapstructure:"mode"`

	// RequiredApprovalRole corresponds to the JSON schema field
	// "requiredApprovalRole".
	RequiredApprovalRole *string `json:"requiredApprovalRole,omitempty,omitzero" yaml:"requiredApprovalRole,omitempty" mapstructure:"requiredApprovalRole,omitempty"`
}
