// Command irgen генерирует Go-представление IR из packages/ir/schema/ir-1.0.schema.json —
// единственного источника истины IR (IR-005):
//
//   - internal/composition/ir/schema_gen.json — копия схемы для go:embed;
//   - internal/composition/ir/types_gen.go — типы Go (go-jsonschema).
//
// Запуск из apps/server: go generate ./internal/composition/ir (или pnpm gen).
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
)

const (
	schemaPath = "../../packages/ir/schema/ir-1.0.schema.json"
	outDir     = "internal/composition/ir"
)

var mapTypes = map[string]string{
	"Design": "// Design — дизайн-свойства узла: имя свойства → DesignValue; ключ \"states\" → DesignStates.\n" +
		"type Design map[string]any\n",
	"ResponsiveValue": "// ResponsiveValue — значение по breakpoint'ам; ключ \"base\" обязателен.\n" +
		"type ResponsiveValue map[string]ScalarDesignValue\n",
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "irgen:", err)
		os.Exit(1)
	}
}

func run() error {
	// go generate запускает команду из каталога пакета; пути считаются от корня модуля.
	gomod, err := exec.Command("go", "env", "GOMOD").Output()
	if err != nil {
		return err
	}
	if err := os.Chdir(filepath.Dir(string(bytes.TrimSpace(gomod)))); err != nil {
		return err
	}

	schema, err := os.ReadFile(schemaPath)
	if err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(outDir, "schema_gen.json"), schema, 0o644); err != nil {
		return err
	}

	tmp, err := os.CreateTemp("", "irgen-*.go")
	if err != nil {
		return err
	}
	tmp.Close()
	defer os.Remove(tmp.Name())

	cmd := exec.Command("go", "tool", "go-jsonschema", "-p", "ir", "--only-models", "-o", tmp.Name(), schemaPath)
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("go-jsonschema: %w", err)
	}
	src, err := os.ReadFile(tmp.Name())
	if err != nil {
		return err
	}

	// Корневой тип называется по имени файла схемы; даём ему имя из спецификации.
	src = regexp.MustCompile(`\bIr10SchemaJson`).ReplaceAll(src, []byte("Document"))
	// go-jsonschema не умеет сочетать именованные свойства со свободными ключами
	// (additionalProperties): свободные ключи попадают в поле, которое encoding/json не
	// заполняет, и теряются. Такие объекты представляем словарями.
	for name, replacement := range mapTypes {
		re := regexp.MustCompile(`(?s)type ` + name + ` struct \{.*?\n\}\n`)
		if !re.Match(src) {
			return fmt.Errorf("тип %s не найден в выводе go-jsonschema", name)
		}
		src = re.ReplaceAll(src, []byte(replacement))
	}

	header := []byte("// Code generated by cmd/irgen from packages/ir/schema/ir-1.0.schema.json. DO NOT EDIT.\n\n")
	src = append(header, bytes.TrimPrefix(src, []byte("// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.\n\n"))...)

	formatted, err := format.Source(src)
	if err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(outDir, "types_gen.go"), formatted, 0o644)
}
